import { StyleSheet } from "react-native";
import { createTokensV2, primaryGlow, shadowsV2, tintFromPrimary } from "@/lib/theme";

export type Tokens = ReturnType<typeof createTokensV2>;
export type ChatStyles = ReturnType<typeof createStyles>;

export function createStyles(tokens: Tokens) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
    },
    keyboardAvoid: {
      flex: 1,
    },
    iconBtn: {
      width: 40,
      height: 40,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyState: {
      flex: 1,
      position: "relative",
    },
    emptyContent: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 16,
      paddingHorizontal: 32,
      zIndex: 1,
    },
    emptyAvatar: {
      width: 84,
      height: 84,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: tintFromPrimary(tokens, 0.16),
      ...primaryGlow(tokens),
    },
    emptyTitle: {
      fontFamily: 'Rubik_500Medium',
      fontSize: 24,
      letterSpacing: -0.24,
      textAlign: "center",
      color: tokens.fg1,
    },
    emptyText: {
      fontFamily: 'Rubik_400Regular',
      fontSize: 15,
      lineHeight: 22,
      maxWidth: 280,
      textAlign: "center",
      color: tokens.fg2,
    },
    aiDisclaimer: {
      fontFamily: 'Rubik_400Regular',
      fontSize: 11,
      lineHeight: 15,
      textAlign: "center",
      maxWidth: 300,
      marginTop: 4,
      color: tokens.fg4,
    },
    messageList: {
      paddingVertical: 16,
    },
    inputArea: {
      borderTopWidth: StyleSheet.hairlineWidth,
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    errorText: {
      fontFamily: 'Rubik_400Regular',
      fontSize: 13,
      textAlign: "center",
      marginBottom: 8,
    },
    retryText: {
      fontFamily: 'Rubik_600SemiBold',
      color: tokens.primary,
    },
    permissionAction: {
      alignSelf: "center",
      marginBottom: 8,
      paddingVertical: 4,
    },
    permissionActionText: {
      fontFamily: 'Rubik_500Medium',
      fontSize: 13,
      textDecorationLine: "underline",
    },
    imagePreviewRow: {
      paddingBottom: 8,
    },
    imagePreviewCard: {
      alignSelf: "flex-start",
      position: "relative",
    },
    imagePreview: {
      width: 64,
      height: 64,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
    },
    imageRemoveButton: {
      position: "absolute",
      top: -4,
      right: -4,
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      alignItems: "center",
      justifyContent: "center",
    },
    quickChipsScroll: {
      marginBottom: 12,
    },
    quickChipsContent: {
      gap: 8,
      paddingRight: 16,
    },
    quickChip: {
      flexDirection: "row",
      alignItems: "center",
      minHeight: 36,
      paddingHorizontal: 16,
      borderRadius: 999,
      backgroundColor: tokens.bgElev,
      borderWidth: 1,
      borderColor: tokens.hairline,
    },
    quickChipPressed: {
      backgroundColor: tokens.bgElev2,
      transform: [{ scale: 0.96 }],
    },
    quickChipText: {
      fontFamily: 'Rubik_500Medium',
      fontSize: 13,
      color: tokens.fg2,
    },
    offlineNotice: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 8,
    },
    offlineText: {
      fontFamily: 'Rubik_400Regular',
      fontSize: 13,
    },
    inputBar: {
      flexDirection: "row",
      alignItems: "flex-end",
      paddingTop: 10,
      gap: 10,
    },
    composerField: {
      flex: 1,
      minWidth: 0,
      minHeight: 50,
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
      borderRadius: 999,
      paddingLeft: 18,
      paddingRight: 8,
      backgroundColor: tokens.bgField,
      borderWidth: 1,
      borderColor: tokens.hairline,
    },
    textInput: {
      flex: 1,
      minWidth: 0,
      minHeight: 0,
      backgroundColor: "transparent",
      borderWidth: 0,
      fontFamily: 'Rubik_400Regular',
      fontSize: 16,
      paddingHorizontal: 0,
      paddingVertical: 13,
      maxHeight: 120,
    },
    fieldIconButton: {
      width: 34,
      height: 34,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
    },
    composerFieldLocked: {
      opacity: 0.45,
    },
    languageControl: {
      position: "relative",
      flexDirection: "row",
      alignItems: "center",
    },
    languageFlagButton: {
      paddingVertical: 4,
      paddingHorizontal: 4,
      borderRadius: 6,
    },
    languageFlagText: {
      fontSize: 12,
    },
    languagePicker: {
      position: "absolute",
      left: 0,
      bottom: 48,
      minWidth: 148,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      paddingVertical: 6,
      backgroundColor: tokens.bgSheet,
      borderColor: tokens.hairline,
      ...shadowsV2.shadow2,
      zIndex: 20,
    },
    languageOption: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    languageOptionFlag: {
      fontSize: 13,
    },
    languageOptionText: {
      fontFamily: 'Rubik_400Regular',
      fontSize: 12,
    },
    languageOptionTextSelected: {
      fontFamily: 'Rubik_600SemiBold',
    },
    recordingContent: {
      flex: 1,
      minWidth: 0,
      minHeight: 50,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 16,
      borderRadius: 999,
      backgroundColor: tokens.bgField,
      borderWidth: 1,
      borderColor: tokens.hairline,
    },
    recordingStatus: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    recordingDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    recordingTime: {
      fontFamily: 'Roboto_500Medium',
      fontSize: 12,
      fontVariant: ["tabular-nums"],
    },
    visualizer: {
      flex: 1,
      minHeight: 24,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    visualizerBar: {
      width: 3,
      height: 20,
      backgroundColor: tokens.fg2,
      borderRadius: 1,
    },
    sendButton: {
      width: 50,
      height: 50,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: tokens.primary,
    },
    sendButtonGlow: {
      ...primaryGlow(tokens),
    },
    sendButtonDisabled: {
      opacity: 0.45,
    },
    sendButtonPressed: {
      transform: [{ scale: 0.94 }],
    },
    stopButton: {
      width: 50,
      height: 50,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: tokens.bgElev,
      borderWidth: 1.5,
      borderColor: tokens.hairlineStrong,
    },
    limitBlock: {
      marginTop: 12,
      gap: 12,
    },
    rewardCard: {
      alignItems: "center",
      gap: 8,
    },
    rewardButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: tokens.hairlineStrong,
    },
    rewardButtonDisabled: {
      opacity: 0.5,
    },
    rewardButtonText: {
      fontFamily: 'Rubik_500Medium',
      fontSize: 13,
      textAlign: "center",
    },
    rewardMeta: {
      fontFamily: 'Roboto_400Regular',
      fontSize: 10,
      textAlign: "center",
      fontVariant: ["tabular-nums"],
    },
    rewardMessage: {
      fontFamily: 'Rubik_500Medium',
      fontSize: 11,
      textAlign: "center",
    },
    usageText: {
      fontFamily: 'Roboto_400Regular',
      fontSize: 10,
      textAlign: "center",
      marginTop: 8,
      fontVariant: ["tabular-nums"],
    },
  });
}
