import { StyleSheet } from 'react-native'
import type { createTokensV2 } from '@/lib/theme'

export type Tokens = ReturnType<typeof createTokensV2>

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  player: { flex: 1 },
  gradientBackdrop: { position: 'absolute', left: 0, right: 0, top: 0, height: 220 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  progressRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6 },
  progressSegment: { flex: 1, height: 3, borderRadius: 2 },
  closeBtn: { width: 36, height: 36, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  closeBtnPressed: { transform: [{ scale: 0.92 }] },
  slide: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    gap: 18,
  },
  eyebrow: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 12,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  heroNumeral: {
    fontFamily: 'Inter_700Bold',
    fontSize: 76,
    lineHeight: 80,
    letterSpacing: -2.3,
    textAlign: 'center',
  },
  label: { fontFamily: 'Rubik_500Medium', fontSize: 17, textAlign: 'center' },
  caption: { fontFamily: 'Rubik_400Regular', fontSize: 14, textAlign: 'center', maxWidth: 280 },
  title: {
    fontFamily: 'Inter_700Bold',
    fontSize: 32,
    lineHeight: 36,
    letterSpacing: -0.6,
    textAlign: 'center',
  },
  bigEmoji: { fontSize: 72, lineHeight: 80, textAlign: 'center' },
  barsRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 10,
    height: 132,
    width: '100%',
    maxWidth: 320,
    marginTop: 6,
  },
  bar: { flex: 1, borderRadius: 7 },
  tapZones: { position: 'absolute', left: 0, right: 0, bottom: 0, top: 56, flexDirection: 'row' },
  prevZone: { flex: 1 },
  nextZone: { flex: 2 },
  shareSlide: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    paddingTop: 8,
    paddingBottom: 28,
    gap: 16,
  },
  shareError: { fontFamily: 'Rubik_400Regular', fontSize: 13, textAlign: 'center' },
  shareCtaWrap: { width: '100%', maxWidth: 360 },
  cover: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingBottom: 32,
    gap: 22,
  },
  coverHeader: { alignItems: 'center', gap: 10 },
  coverTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 38,
    lineHeight: 42,
    letterSpacing: -0.76,
    textAlign: 'center',
  },
  coverSubtitle: { fontFamily: 'Rubik_400Regular', fontSize: 15, textAlign: 'center', maxWidth: 300 },
  periodRow: { flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', gap: 8 },
  ctaWrap: { alignItems: 'center', gap: 12, minHeight: 84 },
  stateText: { fontFamily: 'Rubik_400Regular', fontSize: 14, textAlign: 'center', maxWidth: 300 },
  retryChip: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
  },
  retryChipPressed: { transform: [{ scale: 0.96 }] },
  retryChipText: { fontFamily: 'Rubik_500Medium', fontSize: 13 },
})
