import { StyleSheet } from 'react-native'
import type { createTokensV2 } from '@/lib/theme'

export type Tokens = ReturnType<typeof createTokensV2>

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  player: { flex: 1 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 4,
  },
  slideScrollContent: { flexGrow: 1 },
  page: { flex: 1, position: 'relative' },
  pager: { paddingHorizontal: 16, paddingTop: 16 },
  closeBtn: { width: 44, height: 44, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  closeBtnPressed: { transform: [{ scale: 0.96 }] },
  slide: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    gap: 18,
  },
  eyebrow: {
    fontFamily: 'GeistMono_500Medium',
    fontSize: 12,
    letterSpacing: 0.96,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  heroNumeral: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 44,
    lineHeight: 44,
    letterSpacing: -0.88,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  label: { fontFamily: 'Geist_500Medium', fontSize: 16, textAlign: 'center' },
  caption: { fontFamily: 'Geist_400Regular', fontSize: 14, textAlign: 'center', maxWidth: 280 },
  title: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 34,
    lineHeight: 39,
    letterSpacing: -0.68,
    textAlign: 'center',
  },
  bigEmoji: { fontSize: 72, lineHeight: 80, textAlign: 'center' },
  barsRow: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
    maxWidth: 320,
    marginTop: 6,
  },
  barColumn: { flex: 1, alignItems: 'center', gap: 8 },
  barTrack: { height: 132, width: '100%', justifyContent: 'flex-end' },
  bar: { width: '100%', borderRadius: 7 },
  dayLabel: {
    fontFamily: 'GeistMono_400Regular',
    fontSize: 12,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  tapZones: { position: 'absolute', left: 0, right: 0, bottom: 0, top: 0, flexDirection: 'row' },
  prevZone: { flex: 1 },
  nextZone: { flex: 2 },
  shareSlide: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    paddingTop: 8,
    paddingBottom: 28,
    gap: 16,
  },
  shareError: { fontFamily: 'Geist_400Regular', fontSize: 13, textAlign: 'center' },
  coverScroller: { flex: 1 },
  coverExit: { position: 'absolute', left: 16, top: 8, zIndex: 1 },
  cover: {
    flexGrow: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 32,
    gap: 24,
  },
  coverHeader: { alignItems: 'flex-start', gap: 8 },
  coverEyebrow: {
    fontFamily: 'GeistMono_400Regular',
    fontSize: 12,
    letterSpacing: 0.72,
    textTransform: 'uppercase',
  },
  coverTitle: {
    fontFamily: 'SpaceGrotesk_500Medium',
    fontSize: 34,
    lineHeight: 37,
    letterSpacing: -1.02,
  },
  coverSubtitle: { fontFamily: 'Geist_400Regular', fontSize: 16, lineHeight: 25 },
  periodRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  coverBody: { width: '100%', alignItems: 'stretch', gap: 16 },
  stateText: { flex: 1, fontFamily: 'Geist_400Regular', fontSize: 14, lineHeight: 22, maxWidth: 300 },
  emptyRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
})
