import { StyleSheet } from 'react-native'
import type { createTokensV2 } from '@/lib/theme'

export type Tokens = ReturnType<typeof createTokensV2>

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  player: { flex: 1 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingLeft: 16,
    paddingRight: 8,
    paddingBottom: 8,
  },
  headerCopy: { flex: 1, alignItems: 'flex-start' },
  headerWindow: { fontFamily: 'GeistMono_400Regular', fontSize: 12 },
  slideScrollContent: { flexGrow: 1 },
  page: { flex: 1, position: 'relative' },
  pager: { paddingHorizontal: 16, paddingTop: 16 },
  closeBtn: { width: 44, height: 44, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  closeBtnPressed: { transform: [{ scale: 0.96 }] },
  slide: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 24,
    gap: 8,
  },
  heroNumeral: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 60,
    lineHeight: 60,
    letterSpacing: -1.8,
    fontVariant: ['tabular-nums'],
  },
  streakNumeral: { fontFamily: 'SpaceGrotesk_600SemiBold', fontSize: 44, lineHeight: 44, letterSpacing: -1.32, fontVariant: ['tabular-nums'] },
  label: { fontFamily: 'Geist_400Regular', fontSize: 20 },
  caption: { fontFamily: 'Geist_400Regular', fontSize: 16, lineHeight: 25 },
  weekdayReading: { fontFamily: 'Geist_400Regular', fontSize: 16, lineHeight: 25 },
  weekdayNote: { fontFamily: 'Geist_400Regular', fontSize: 14, lineHeight: 22 },
  title: {
    fontFamily: 'SpaceGrotesk_500Medium',
    fontSize: 28,
    lineHeight: 32,
    letterSpacing: -0.56,
  },
  introTitle: { fontFamily: 'SpaceGrotesk_500Medium', fontSize: 34, lineHeight: 37, letterSpacing: -1.02 },
  topHabitTitle: { fontFamily: 'SpaceGrotesk_500Medium', fontSize: 34, lineHeight: 37, letterSpacing: -0.68 },
  introSlide: { gap: 16 },
  weekdaySlide: { gap: 24 },
  streakSlide: { gap: 24 },
  topHabitSlide: { gap: 16 },
  habitWell: { width: 88, height: 88, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  habitEmoji: { fontSize: 44, lineHeight: 53 },
  habitInitial: { fontFamily: 'SpaceGrotesk_500Medium', fontSize: 44, lineHeight: 53 },
  figureWidth: { width: '100%' },
  tapZones: { position: 'absolute', left: 0, right: 0, bottom: 0, top: 0, flexDirection: 'row' },
  prevZone: { flex: 1 },
  nextZone: { flex: 2 },
  shareSlide: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 24,
    gap: 16,
  },
  shareError: { fontFamily: 'Geist_400Regular', fontSize: 13 },
  shareStatus: { fontFamily: 'GeistMono_400Regular', fontSize: 13 },
  sharePreview: { width: 216, height: 384, overflow: 'hidden' },
  sharePreviewCard: { width: 360, height: 640, transform: [{ scale: 0.6 }], transformOrigin: 'top left' },
  shareActions: { flexDirection: 'column', alignItems: 'stretch', gap: 8 },
  coverScroller: { flex: 1 },
  coverExit: { position: 'absolute', left: 16, zIndex: 1 },
  cover: {
    flexGrow: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 32,
    gap: 24,
  },
  coverHeader: { alignItems: 'flex-start', gap: 8 },
  coverEyebrow: {
    fontFamily: 'GeistMono_400Regular',
    fontSize: 12,
    letterSpacing: 0.72,
    textTransform: 'uppercase',
  },
  coverTitle: {
    fontFamily: 'SpaceGrotesk_500Medium',
    fontSize: 34,
    lineHeight: 37,
    letterSpacing: -1.02,
  },
  coverSubtitle: { fontFamily: 'Geist_400Regular', fontSize: 16, lineHeight: 25 },
  periodRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  coverBody: { width: '100%', alignItems: 'stretch', gap: 16 },
  stateText: { flex: 1, fontFamily: 'Geist_400Regular', fontSize: 14, lineHeight: 22, maxWidth: 300 },
  emptyRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
})
