// Generated by apps/mobile/scripts/generate-widget-colors.ts. Do not edit.
package org.useorbit.app.widget

internal object WidgetColorFallbacks {
    val dark = mapOf(
        "background" to "#131315", // WHY: --bg-card flattened over --bg.
        "surface" to "#1D1D1F", // WHY: --bg-well flattened over --bg.
        "surfaceGround" to "#09090B", // WHY: --bg.
        "textPrimary" to "#F4F4F6", // WHY: --fg-1.
        "textSecondary" to "#C9C9CC", // WHY: --fg-2.
        "textMuted" to "#8F8F93", // WHY: --fg-3.
        "border" to "#2B2B2D", // WHY: --hairline-ghost flattened over --bg-card.
        "borderMuted" to "#2B2B2D", // WHY: --hairline-ghost flattened over --bg-card.
        "overdue" to "#FE9A00", // WHY: --status-overdue.
        "streak" to "#C4530F", // WHY: --primary.
        "streakText" to "#F4F4F6", // WHY: --fg-1.
        "statusEmpty" to "#5D5D60", // WHY: --fg-4.
    )

    val light = mapOf(
        "background" to "#FFFFFF", // WHY: --bg-card.
        "surface" to "#F1F1F2", // WHY: --bg-well flattened over --bg.
        "surfaceGround" to "#FAFAFA", // WHY: --bg.
        "textPrimary" to "#1A1A1D", // WHY: --fg-1.
        "textSecondary" to "#424247", // WHY: --fg-2.
        "textMuted" to "#68686D", // WHY: --fg-3.
        "border" to "#E6E6E8", // WHY: --hairline flattened over --bg-card.
        "borderMuted" to "#E6E6E8", // WHY: --hairline flattened over --bg-card.
        "overdue" to "#886100", // WHY: --status-overdue.
        "streak" to "#C4530F", // WHY: --primary.
        "streakText" to "#1A1A1D", // WHY: --fg-1.
        "statusEmpty" to "#89898D", // WHY: --fg-4.
    )
}
