import React from 'react'

type IconProps = Readonly<Record<string, unknown>>

function createIcon(name: string) {
  return function Icon(props: IconProps) {
    return React.createElement(name, props)
  }
}

export const Activity = createIcon('Activity')
export const AlarmClock = createIcon('AlarmClock')
export const Apple = createIcon('Apple')
export const ArrowRight = createIcon('ArrowRight')
export const BedDouble = createIcon('BedDouble')
export const Bell = createIcon('Bell')
export const Bike = createIcon('Bike')
export const Book = createIcon('Book')
export const BookOpen = createIcon('BookOpen')
export const Brain = createIcon('Brain')
export const Briefcase = createIcon('Briefcase')
export const Brush = createIcon('Brush')
export const CalendarDays = createIcon('CalendarDays')
export const Camera = createIcon('Camera')
export const Car = createIcon('Car')
export const Check = createIcon('Check')
export const CheckCircle2 = createIcon('CheckCircle2')
export const ChevronDown = createIcon('ChevronDown')
export const ChevronLeft = createIcon('ChevronLeft')
export const ChevronRight = createIcon('ChevronRight')
export const ChevronsDownUp = createIcon('ChevronsDownUp')
export const ChevronsUpDown = createIcon('ChevronsUpDown')
export const ClipboardCheck = createIcon('ClipboardCheck')
export const ClipboardList = createIcon('ClipboardList')
export const Coffee = createIcon('Coffee')
export const Cookie = createIcon('Cookie')
export const Copy = createIcon('Copy')
export const Droplet = createIcon('Droplet')
export const Dumbbell = createIcon('Dumbbell')
export const Eye = createIcon('Eye')
export const FastForward = createIcon('FastForward')
export const Flame = createIcon('Flame')
export const Footprints = createIcon('Footprints')
export const GlassWater = createIcon('GlassWater')
export const Guitar = createIcon('Guitar')
export const HandHeart = createIcon('HandHeart')
export const Headphones = createIcon('Headphones')
export const Heart = createIcon('Heart')
export const HeartPulse = createIcon('HeartPulse')
export const Home = createIcon('Home')
export const Laptop = createIcon('Laptop')
export const Leaf = createIcon('Leaf')
export const Lightbulb = createIcon('Lightbulb')
export const MessageCircle = createIcon('MessageCircle')
export const MinusCircle = createIcon('MinusCircle')
export const Moon = createIcon('Moon')
export const MoreVertical = createIcon('MoreVertical')
export const Music = createIcon('Music')
export const Newspaper = createIcon('Newspaper')
export const Palette = createIcon('Palette')
export const Pencil = createIcon('Pencil')
export const PenLine = createIcon('PenLine')
export const PersonStanding = createIcon('PersonStanding')
export const PiggyBank = createIcon('PiggyBank')
export const Pill = createIcon('Pill')
export const Pizza = createIcon('Pizza')
export const Plus = createIcon('Plus')
export const PlusCircle = createIcon('PlusCircle')
export const RefreshCw = createIcon('RefreshCw')
export const Search = createIcon('Search')
export const ShoppingBag = createIcon('ShoppingBag')
export const SkipForward = createIcon('SkipForward')
export const Smile = createIcon('Smile')
export const Sparkles = createIcon('Sparkles')
export const Sprout = createIcon('Sprout')
export const Star = createIcon('Star')
export const Sun = createIcon('Sun')
export const Target = createIcon('Target')
export const Trash2 = createIcon('Trash2')
export const Trophy = createIcon('Trophy')
export const User = createIcon('User')
export const Users = createIcon('Users')
export const Utensils = createIcon('Utensils')
export const Waves = createIcon('Waves')
export const Wind = createIcon('Wind')
export const X = createIcon('X')
export const Zap = createIcon('Zap')

// Type alias for LucideIcon so the catalog compiles in tests
export type LucideIcon = ReturnType<typeof createIcon>
