import React from 'react'

type IconProps = Readonly<Record<string, unknown>>

function createIcon(name: string) {
  return function Icon(props: IconProps) {
    return React.createElement(name, props)
  }
}

export const AlertTriangle = createIcon('AlertTriangle')
export const ArrowRight = createIcon('ArrowRight')
export const BarChart3 = createIcon('BarChart3')
export const Bell = createIcon('Bell')
export const BellRing = createIcon('BellRing')
export const Brain = createIcon('Brain')
export const Calendar = createIcon('Calendar')
export const CalendarCheck = createIcon('CalendarCheck')
export const CalendarClock = createIcon('CalendarClock')
export const ChartLine = createIcon('ChartLine')
export const Check = createIcon('Check')
export const CheckCheck = createIcon('CheckCheck')
export const CheckCircle2 = createIcon('CheckCircle2')
export const CalendarDays = createIcon('CalendarDays')
export const ChevronDown = createIcon('ChevronDown')
export const ChevronLeft = createIcon('ChevronLeft')
export const ChevronRight = createIcon('ChevronRight')
export const ChevronsDownUp = createIcon('ChevronsDownUp')
export const ChevronsLeft = createIcon('ChevronsLeft')
export const ChevronsRight = createIcon('ChevronsRight')
export const ChevronsUpDown = createIcon('ChevronsUpDown')
export const ClipboardCheck = createIcon('ClipboardCheck')
export const ClipboardList = createIcon('ClipboardList')
export const Clock3 = createIcon('Clock3')
export const Copy = createIcon('Copy')
export const Expand = createIcon('Expand')
export const Eye = createIcon('Eye')
export const FastForward = createIcon('FastForward')
export const FileText = createIcon('FileText')
export const Flame = createIcon('Flame')
export const Gift = createIcon('Gift')
export const HelpCircle = createIcon('HelpCircle')
export const Home = createIcon('Home')
export const Infinity = createIcon('Infinity')
export const ListChecks = createIcon('ListChecks')
export const Lock = createIcon('Lock')
export const MessageCircle = createIcon('MessageCircle')
export const MessageSquare = createIcon('MessageSquare')
export const MinusCircle = createIcon('MinusCircle')
export const MoreVertical = createIcon('MoreVertical')
export const Orbit = createIcon('Orbit')
export const Palette = createIcon('Palette')
export const Paperclip = createIcon('Paperclip')
export const Pencil = createIcon('Pencil')
export const PenSquare = createIcon('PenSquare')
export const Plus = createIcon('Plus')
export const PlusCircle = createIcon('PlusCircle')
export const RefreshCw = createIcon('RefreshCw')
export const Repeat = createIcon('Repeat')
export const Satellite = createIcon('Satellite')
export const Search = createIcon('Search')
export const Share2 = createIcon('Share2')
export const ShieldAlert = createIcon('ShieldAlert')
export const ShieldCheck = createIcon('ShieldCheck')
export const Shuffle = createIcon('Shuffle')
export const Sparkles = createIcon('Sparkles')
export const SquareX = createIcon('SquareX')
export const Tag = createIcon('Tag')
export const Trash2 = createIcon('Trash2')
export const TrendingDown = createIcon('TrendingDown')
export const TrendingUp = createIcon('TrendingUp')
export const Trophy = createIcon('Trophy')
export const Upload = createIcon('Upload')
export const User = createIcon('User')
export const UserPlus = createIcon('UserPlus')
export const Users = createIcon('Users')
export const WifiOff = createIcon('WifiOff')
export const X = createIcon('X')
