import {
  Activity,
  AlarmClock,
  Apple,
  BedDouble,
  Bike,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Camera,
  Car,
  Coffee,
  Cookie,
  Droplet,
  Dumbbell,
  Flame,
  Footprints,
  GlassWater,
  Guitar,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Laptop,
  Leaf,
  Lightbulb,
  MessageCircle,
  Moon,
  Music,
  Newspaper,
  Palette,
  PenLine,
  PersonStanding,
  PiggyBank,
  Pill,
  Pizza,
  ShoppingBag,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Target,
  Trophy,
  Users,
  Utensils,
  Waves,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Ordered list of lucide icon keys curated for habit selection.
 * Keep keys aligned with apps/mobile/lib/habit-icon-catalog.ts.
 */
export const HABIT_ICON_KEYS = [
  'flame',
  'dumbbell',
  'bike',
  'footprints',
  'person-standing',
  'heart-pulse',
  'activity',
  'droplet',
  'glass-water',
  'waves',
  'apple',
  'utensils',
  'pizza',
  'cookie',
  'coffee',
  'book',
  'book-open',
  'pen-line',
  'newspaper',
  'brain',
  'lightbulb',
  'target',
  'trophy',
  'star',
  'sparkles',
  'sun',
  'moon',
  'bed-double',
  'alarm-clock',
  'zap',
  'leaf',
  'sprout',
  'wind',
  'heart',
  'smile',
  'hand-heart',
  'users',
  'message-circle',
  'music',
  'guitar',
  'headphones',
  'palette',
  'brush',
  'camera',
  'home',
  'shopping-bag',
  'piggy-bank',
  'briefcase',
  'laptop',
  'car',
  'pill',
] as const

export type HabitIconKey = (typeof HABIT_ICON_KEYS)[number]

export const HABIT_ICON_MAP: Record<HabitIconKey, LucideIcon> = {
  flame: Flame,
  dumbbell: Dumbbell,
  bike: Bike,
  footprints: Footprints,
  'person-standing': PersonStanding,
  'heart-pulse': HeartPulse,
  activity: Activity,
  droplet: Droplet,
  'glass-water': GlassWater,
  waves: Waves,
  apple: Apple,
  utensils: Utensils,
  pizza: Pizza,
  cookie: Cookie,
  coffee: Coffee,
  book: Book,
  'book-open': BookOpen,
  'pen-line': PenLine,
  newspaper: Newspaper,
  brain: Brain,
  lightbulb: Lightbulb,
  target: Target,
  trophy: Trophy,
  star: Star,
  sparkles: Sparkles,
  sun: Sun,
  moon: Moon,
  'bed-double': BedDouble,
  'alarm-clock': AlarmClock,
  zap: Zap,
  leaf: Leaf,
  sprout: Sprout,
  wind: Wind,
  heart: Heart,
  smile: Smile,
  'hand-heart': HandHeart,
  users: Users,
  'message-circle': MessageCircle,
  music: Music,
  guitar: Guitar,
  headphones: Headphones,
  palette: Palette,
  brush: Brush,
  camera: Camera,
  home: Home,
  'shopping-bag': ShoppingBag,
  'piggy-bank': PiggyBank,
  briefcase: Briefcase,
  laptop: Laptop,
  car: Car,
  pill: Pill,
}

export function resolveHabitIcon(key: string | null | undefined): LucideIcon | null {
  if (!key) return null
  return HABIT_ICON_MAP[key as HabitIconKey] ?? null
}
