import type { HabitScheduleItem } from '../types/habit'
import type { Goal } from '../types/goal'

// ---------------------------------------------------------------------------
// Mock data factories for the guided tour
// All IDs prefixed with "tour-" to prevent collision with real data.
// Accepts a translator function so mock data matches the user's locale.
// ---------------------------------------------------------------------------

type T = (key: string) => string

export function createTourMockTags(t: T) {
  return [
    { id: 'tour-tag-1', name: t('tour.mockData.tags.mindfulness'), color: '#8b5cf6' },
    { id: 'tour-tag-2', name: t('tour.mockData.tags.health'), color: '#22c55e' },
    { id: 'tour-tag-3', name: t('tour.mockData.tags.learning'), color: '#3b82f6' },
  ]
}

export function createTourMockHabits(today: string, t: T): HabitScheduleItem[] {
  const allTags = createTourMockTags(t)
  const mindfulness = allTags[0]!
  const health = allTags[1]!
  const learning = allTags[2]!

  return [
    {
      id: 'tour-habit-1',
      title: t('tour.mockData.habits.meditation.title'),
      description: t('tour.mockData.habits.meditation.description'),
      frequencyUnit: 'Day',
      frequencyQuantity: 1,
      isBadHabit: false,
      isCompleted: true,
      isGeneral: false,
      isFlexible: false,
      days: [],
      dueDate: today,
      dueTime: '07:00',
      dueEndTime: null,
      endDate: null,
      position: 0,
      checklistItems: [],
      createdAtUtc: '2025-01-01T00:00:00Z',
      scheduledDates: [today],
      isOverdue: false,
      reminderEnabled: true,
      reminderTimes: [0],
      scheduledReminders: [],
      slipAlertEnabled: false,
      tags: [mindfulness],
      children: [],
      hasSubHabits: false,
      flexibleTarget: null,
      flexibleCompleted: null,
      linkedGoals: [],
      instances: [{ date: today, status: 'Completed', logId: 'tour-log-1', note: null }],
    },
    {
      id: 'tour-habit-2',
      title: t('tour.mockData.habits.exercise.title'),
      description: t('tour.mockData.habits.exercise.description'),
      frequencyUnit: 'Week',
      frequencyQuantity: 3,
      isBadHabit: false,
      isCompleted: false,
      isGeneral: false,
      isFlexible: false,
      days: ['Monday', 'Wednesday', 'Friday'],
      dueDate: today,
      dueTime: '18:00',
      dueEndTime: null,
      endDate: null,
      position: 1,
      checklistItems: [
        { text: t('tour.mockData.checklists.warmUp'), isChecked: false },
        { text: t('tour.mockData.checklists.mainWorkout'), isChecked: false },
        { text: t('tour.mockData.checklists.coolDown'), isChecked: false },
      ],
      createdAtUtc: '2025-01-01T00:00:00Z',
      scheduledDates: [today],
      isOverdue: false,
      reminderEnabled: true,
      reminderTimes: [15],
      scheduledReminders: [],
      slipAlertEnabled: false,
      tags: [health],
      children: [
        {
          id: 'tour-habit-2a',
          title: t('tour.mockData.habits.pushups.title'),
          description: null,
          frequencyUnit: 'Week',
          frequencyQuantity: 3,
          isBadHabit: false,
          isCompleted: false,
          isGeneral: false,
          isFlexible: false,
          days: [],
          dueDate: today,
          dueTime: null,
          dueEndTime: null,
          endDate: null,
          position: 0,
          checklistItems: [],
          tags: [],
          children: [],
          hasSubHabits: false,
          isLoggedInRange: false,
          instances: [{ date: today, status: 'Pending', logId: null, note: null }],
        },
        {
          id: 'tour-habit-2b',
          title: t('tour.mockData.habits.stretching.title'),
          description: null,
          frequencyUnit: 'Week',
          frequencyQuantity: 3,
          isBadHabit: false,
          isCompleted: false,
          isGeneral: false,
          isFlexible: false,
          days: [],
          dueDate: today,
          dueTime: null,
          dueEndTime: null,
          endDate: null,
          position: 1,
          checklistItems: [],
          tags: [],
          children: [],
          hasSubHabits: false,
          isLoggedInRange: false,
          instances: [{ date: today, status: 'Pending', logId: null, note: null }],
        },
      ],
      hasSubHabits: true,
      flexibleTarget: null,
      flexibleCompleted: null,
      linkedGoals: [{ id: 'tour-goal-1', title: t('tour.mockData.goals.marathon.title') }],
      instances: [{ date: today, status: 'Pending', logId: null, note: null }],
    },
    {
      id: 'tour-habit-3',
      title: t('tour.mockData.habits.screenTime.title'),
      description: t('tour.mockData.habits.screenTime.description'),
      frequencyUnit: 'Day',
      frequencyQuantity: 1,
      isBadHabit: true,
      isCompleted: false,
      isGeneral: false,
      isFlexible: false,
      days: [],
      dueDate: today,
      dueTime: null,
      dueEndTime: null,
      endDate: null,
      position: 2,
      checklistItems: [],
      createdAtUtc: '2025-01-15T00:00:00Z',
      scheduledDates: [today],
      isOverdue: false,
      reminderEnabled: false,
      reminderTimes: [],
      scheduledReminders: [],
      slipAlertEnabled: true,
      tags: [health],
      children: [],
      hasSubHabits: false,
      flexibleTarget: null,
      flexibleCompleted: null,
      linkedGoals: [],
      instances: [{ date: today, status: 'Pending', logId: null, note: null }],
    },
    {
      id: 'tour-habit-4',
      title: t('tour.mockData.habits.readBooks.title'),
      description: t('tour.mockData.habits.readBooks.description'),
      frequencyUnit: 'Week',
      frequencyQuantity: 5,
      isBadHabit: false,
      isCompleted: false,
      isGeneral: false,
      isFlexible: true,
      days: [],
      dueDate: today,
      dueTime: null,
      dueEndTime: null,
      endDate: null,
      position: 3,
      checklistItems: [],
      createdAtUtc: '2025-02-01T00:00:00Z',
      scheduledDates: [today],
      isOverdue: false,
      reminderEnabled: false,
      reminderTimes: [],
      scheduledReminders: [],
      slipAlertEnabled: false,
      tags: [learning],
      children: [],
      hasSubHabits: false,
      flexibleTarget: 5,
      flexibleCompleted: 3,
      linkedGoals: [{ id: 'tour-goal-2', title: t('tour.mockData.goals.readGoal.title') }],
      instances: [{ date: today, status: 'Pending', logId: null, note: null }],
    },
    {
      id: 'tour-habit-5',
      title: t('tour.mockData.habits.drinkWater.title'),
      description: t('tour.mockData.habits.drinkWater.description'),
      frequencyUnit: null,
      frequencyQuantity: null,
      isBadHabit: false,
      isCompleted: false,
      isGeneral: true,
      isFlexible: false,
      days: [],
      dueDate: today,
      dueTime: null,
      dueEndTime: null,
      endDate: null,
      position: 4,
      checklistItems: [],
      createdAtUtc: '2025-03-01T00:00:00Z',
      scheduledDates: [],
      isOverdue: false,
      reminderEnabled: false,
      reminderTimes: [],
      scheduledReminders: [],
      slipAlertEnabled: false,
      tags: [health],
      children: [],
      hasSubHabits: false,
      flexibleTarget: null,
      flexibleCompleted: null,
      linkedGoals: [],
      instances: [],
    },
  ]
}

export function createTourMockGoals(t: T): Goal[] {
  return [
    {
      id: 'tour-goal-1',
      title: t('tour.mockData.goals.marathon.title'),
      description: t('tour.mockData.goals.marathon.description'),
      targetValue: 42,
      currentValue: 28,
      unit: 'km',
      type: 'Standard',
      status: 'Active',
      deadline: '2025-12-31',
      position: 0,
      createdAtUtc: '2025-01-01T00:00:00Z',
      completedAtUtc: null,
      progressPercentage: 67,
      trackingStatus: 'on_track',
      linkedHabits: [{ id: 'tour-habit-2', title: t('tour.mockData.habits.exercise.title') }],
    },
    {
      id: 'tour-goal-2',
      title: t('tour.mockData.goals.readGoal.title'),
      description: t('tour.mockData.goals.readGoal.description'),
      targetValue: 24,
      currentValue: 12,
      unit: 'books',
      type: 'Standard',
      status: 'Active',
      deadline: '2025-12-31',
      position: 1,
      createdAtUtc: '2025-01-01T00:00:00Z',
      completedAtUtc: null,
      progressPercentage: 50,
      trackingStatus: 'on_track',
      linkedHabits: [{ id: 'tour-habit-4', title: t('tour.mockData.habits.readBooks.title') }],
    },
  ]
}
