import { defineConfig } from 'vitest/config'
import path from 'path'

export default defineConfig({
  test: {
    environment: 'node',
    globals: true,
    setupFiles: ['./test-setup.ts'],
    include: ['__tests__/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      reportsDirectory: './coverage',
      include: [
        'app/**/*.{ts,tsx}',
        'components/**/*.{ts,tsx}',
        'hooks/**/*.{ts,tsx}',
        'stores/**/*.ts',
        'lib/**/*.{ts,tsx}',
        'modules/orbit-widget/src/**/*.{ts,tsx}',
      ],
      exclude: [
        '**/*.d.ts',
        '**/*.styles.ts',
        '**/*-styles.ts',
        '**/styles.ts',
        'app/**/_layout.tsx',
        'app/(onboarding)/index.tsx',
        'app/(tabs)/calendar/_components/calendar-day-entry.tsx',
        'app/(tabs)/calendar/_components/calendar-grid.tsx',
        'app/(tabs)/today-shell.tsx',
        'app/+not-found.tsx',
        'app/about.tsx',
        'app/accountability-pair.tsx',
        'app/advanced-sections.tsx',
        'app/advanced.tsx',
        'app/ai-settings.tsx',
        'app/auth-callback.tsx',
        'app/chat.tsx',
        'app/code-step.tsx',
        'app/email-step.tsx',
        'app/login-atoms.tsx',
        'app/login.tsx',
        'app/preferences-labels.ts',
        'app/preferences-sections.tsx',
        'app/preferences.tsx',
        'app/privacy.tsx',
        'app/r/[code].tsx',
        'app/retrospective-empty-state.tsx',
        'app/retrospective-no-data-state.tsx',
        'app/social.tsx',
        'app/social/_components/add-friend-form.tsx',
        'app/social/_components/buddy-invite-row.tsx',
        'app/social/_components/buddy-row.tsx',
        'app/social/_components/challenges-entry-card.tsx',
        'app/social/_components/cheer-composer.tsx',
        'app/social/_components/friend-request-row.tsx',
        'app/social/_components/invite-hero.tsx',
        'app/social/_components/social-opt-in-gate.tsx',
        'app/social/challenges/[id].tsx',
        'app/social/challenges/_components/challenge-card.tsx',
        'app/social/challenges/_components/habit-picker.tsx',
        'app/social/challenges/_components/invite-friends-picker.tsx',
        'app/social/challenges/_components/share-join-code.tsx',
        'app/streak-sections-freeze.tsx',
        'app/streak-sections.tsx',
        'app/streak.tsx',
        'app/terms.tsx',
        'app/wrapped-cover.tsx',
        'app/wrapped-player.tsx',
        'app/wrapped-slide.tsx',
        'app/wrapped.tsx',
        'components/chat/chat-animations.tsx',
        'components/chat/chat-empty-state.tsx',
        'components/chat/chat-input-area.tsx',
        'components/chat/conflict-warning.tsx',
        'components/chat/suggestion-chips.tsx',
        'components/chat/typing-indicator.tsx',
        'components/gamification/achievement-toast.tsx',
        'components/gamification/all-done-celebration.tsx',
        'components/gamification/celebration-motion.ts',
        'components/gamification/goal-completed-celebration.tsx',
        'components/gamification/level-up-overlay.tsx',
        'components/gamification/ring-motif.tsx',
        'components/gamification/streak-freeze-celebration.tsx',
        'components/gamification/welcome-back-toast.tsx',
        'components/goals/create-goal-modal.tsx',
        'components/goals/create-goal-modal/goal-deadline-field.tsx',
        'components/goals/create-goal-modal/goal-target-fields.tsx',
        'components/goals/create-goal-modal/goal-type-selector.tsx',
        'components/goals/edit-goal-modal.tsx',
        'components/goals/edit-goal-modal/edit-goal-deadline-field.tsx',
        'components/goals/edit-goal-modal/edit-goal-target-fields.tsx',
        'components/goals/goal-metrics-panel.tsx',
        'components/goals/goals-view.tsx',
        'components/habit-list/drill-panel.tsx',
        'components/habits/checklist-templates.tsx',
        'components/habits/description-viewer.tsx',
        'components/habits/goal-linking-field.tsx',
        'components/habits/habit-calendar.tsx',
        'components/habits/habit-checklist.tsx',
        'components/habits/habit-form-fields/active-days-section.tsx',
        'components/habits/habit-form-fields/choice-button-row.tsx',
        'components/habits/habit-form-fields/slip-alert-section.tsx',
        'components/habits/habit-form-fields/tag-color-picker.tsx',
        'components/habits/habit-form-fields/tag-editor-row.tsx',
        'components/milestone-share/milestone-share-card.tsx',
        'components/navigation/bottom-tab-bar.tsx',
        'components/navigation/notification-detail-modal.tsx',
        'components/onboarding/feature-guide-drawer.tsx',
        'components/onboarding/onboarding-complete-habit.tsx',
        'components/onboarding/onboarding-complete.tsx',
        'components/onboarding/onboarding-create-goal.tsx',
        'components/onboarding/onboarding-create-habit.tsx',
        'components/onboarding/onboarding-features.tsx',
        'components/onboarding/onboarding-welcome.tsx',
        'components/profile/profile-nav-icon.tsx',
        'components/referral/referral-card.tsx',
        'components/referral/referral-drawer.tsx',
        'components/social/social-entry-card.tsx',
        'components/tour/tour-overlay.tsx',
        'components/tour/tour-provider.tsx',
        'components/tour/tour-replay-modal.tsx',
        'components/tour/tour-spotlight.tsx',
        'components/tour/tour-tooltip.tsx',
        'components/ui/app-date-picker.tsx',
        'components/ui/app-select.tsx',
        'components/ui/app-toast.tsx',
        'components/ui/bottom-sheet-app-text-input.tsx',
        'components/ui/expiry-warning.tsx',
        'components/ui/fresh-start-animation.tsx',
        'components/ui/highlight-text.tsx',
        'components/ui/mono-toggle.tsx',
        'components/ui/tag-chip.tsx',
        'components/ui/theme-toggle.tsx',
        'components/ui/trial-banner.tsx',
        'components/ui/trial-expired-modal.tsx',
        'components/ui/year-picker.tsx',
        'components/upgrade/plan-summary-card.tsx',
        'components/upgrade/play-billing-dashboard.tsx',
        'components/upgrade/pro-active-panel.tsx',
        'components/upgrade/usage-card.tsx',
        'components/version-update-drawer.tsx',
        'hooks/use-app-toast.ts',
        'hooks/use-date-format.ts',
        'hooks/use-habit-visibility.ts',
        'hooks/use-horizontal-swipe.ts',
        'hooks/use-undo-toast.ts',
        'lib/orbit-widget.ts',
        'lib/plural.ts',
        'lib/providers.tsx',
        'lib/sentry-init.ts',
        'lib/supabase.ts',
        'lib/theme-provider.tsx',
        'lib/use-app-theme.ts',
        'modules/orbit-widget/src/OrbitWidgetModule.ts',
        'modules/orbit-widget/src/OrbitWidgetModule.web.ts',
        'modules/orbit-widget/src/OrbitWidgetView.tsx',
        'modules/orbit-widget/src/OrbitWidgetView.web.tsx',
        'stores/version-gate-store.ts',
      ],
      thresholds: {
        statements: 81,
        branches: 65,
        functions: 73,
        lines: 82,
      },
    },
  },
  resolve: {
    alias: [
      {
        find: 'react-native/Libraries/Animated/NativeAnimatedHelper',
        replacement: path.resolve(__dirname, './test-mocks/native-animated-helper.ts'),
      },
      {
        find: /^react-native(\/.*)?$/,
        replacement: path.resolve(__dirname, './test-mocks/react-native.ts'),
      },
      {
        find: 'react-native-safe-area-context',
        replacement: path.resolve(__dirname, './test-mocks/react-native-safe-area-context.ts'),
      },
      {
        find: 'lucide-react-native',
        replacement: path.resolve(__dirname, './test-mocks/lucide-react-native.ts'),
      },
      {
        find: 'react-native-svg',
        replacement: path.resolve(__dirname, './test-mocks/react-native-svg.ts'),
      },
      {
        find: '@react-native-async-storage/async-storage',
        replacement: path.resolve(__dirname, './test-mocks/async-storage.ts'),
      },
      {
        find: '@react-native-community/netinfo',
        replacement: path.resolve(__dirname, './test-mocks/netinfo.ts'),
      },
      {
        find: 'react-native-gesture-handler',
        replacement: path.resolve(__dirname, './test-mocks/react-native-gesture-handler.ts'),
      },
      {
        find: 'react-native-reanimated',
        replacement: path.resolve(__dirname, './test-mocks/react-native-reanimated.ts'),
      },
      {
        find: 'react-native-worklets',
        replacement: path.resolve(__dirname, './test-mocks/react-native-worklets.ts'),
      },
      {
        find: 'expo-blur',
        replacement: path.resolve(__dirname, './test-mocks/expo-blur.ts'),
      },
      {
        find: 'expo-notifications',
        replacement: path.resolve(__dirname, './test-mocks/expo-notifications.ts'),
      },
      {
        find: 'expo-constants',
        replacement: path.resolve(__dirname, './test-mocks/expo-constants.ts'),
      },
      {
        find: 'expo-store-review',
        replacement: path.resolve(__dirname, './test-mocks/expo-store-review.ts'),
      },
      {
        find: 'expo-clipboard',
        replacement: path.resolve(__dirname, './test-mocks/expo-clipboard.ts'),
      },
      {
        find: 'expo-file-system',
        replacement: path.resolve(__dirname, './test-mocks/expo-file-system.ts'),
      },
      {
        find: 'react-native-view-shot',
        replacement: path.resolve(__dirname, './test-mocks/react-native-view-shot.ts'),
      },
      {
        find: 'expo-sharing',
        replacement: path.resolve(__dirname, './test-mocks/expo-sharing.ts'),
      },
      {
        find: 'react-native-qrcode-svg',
        replacement: path.resolve(__dirname, './test-mocks/react-native-qrcode-svg.ts'),
      },
      {
        find: 'expo-iap',
        replacement: path.resolve(__dirname, './test-mocks/expo-iap.ts'),
      },
      {
        find: /\.(png|jpg|jpeg|gif|webp)$/,
        replacement: path.resolve(__dirname, './test-mocks/file-asset.ts'),
      },
      {
        find: 'nativewind/jsx-dev-runtime',
        replacement: path.resolve(__dirname, './test-mocks/react-jsx-dev-runtime.ts'),
      },
      {
        find: 'nativewind/jsx-runtime',
        replacement: path.resolve(__dirname, './test-mocks/react-jsx-runtime.ts'),
      },
      {
        find: /^date-fns$/,
        replacement: path.resolve(__dirname, './test-mocks/date-fns.ts'),
      },
      {
        find: /^date-fns\/locale$/,
        replacement: path.resolve(__dirname, './test-mocks/date-fns-locale.ts'),
      },
      {
        find: '@/lib/use-app-theme',
        replacement: path.resolve(__dirname, './test-mocks/use-app-theme.ts'),
      },
      {
        find: '@/lib/theme-provider',
        replacement: path.resolve(__dirname, './test-mocks/theme-provider.ts'),
      },
      {
        find: '@orbit/shared/utils/dates',
        replacement: path.resolve(__dirname, './test-mocks/shared-dates.ts'),
      },
      {
        find: 'react-native-css-interop/jsx-dev-runtime',
        replacement: path.resolve(__dirname, './test-mocks/react-jsx-dev-runtime.ts'),
      },
      {
        find: 'react-native-css-interop/jsx-runtime',
        replacement: path.resolve(__dirname, './test-mocks/react-jsx-runtime.ts'),
      },
      { find: '@', replacement: path.resolve(__dirname) },
      {
        find: '@orbit/shared/utils/onboarding',
        replacement: path.resolve(__dirname, './test-mocks/onboarding-utils.ts'),
      },
      {
        find: '@orbit/shared/utils/error-utils',
        replacement: path.resolve(__dirname, './test-mocks/error-utils.ts'),
      },
      { find: '@orbit/shared', replacement: path.resolve(__dirname, '../../packages/shared/src') },
      { find: '@orbit/shared/utils', replacement: path.resolve(__dirname, '../../packages/shared/src/utils') },
      { find: /^@orbit\/shared\/utils\/(.*)$/, replacement: path.resolve(__dirname, '../../packages/shared/src/utils/$1') },
      { find: '@orbit/shared/api', replacement: path.resolve(__dirname, '../../packages/shared/src/api') },
      { find: /^@orbit\/shared\/api\/(.*)$/, replacement: path.resolve(__dirname, '../../packages/shared/src/api/$1') },
      { find: '@orbit/shared/query', replacement: path.resolve(__dirname, '../../packages/shared/src/query') },
      { find: /^@orbit\/shared\/query\/(.*)$/, replacement: path.resolve(__dirname, '../../packages/shared/src/query/$1') },
      { find: '@orbit/shared/theme', replacement: path.resolve(__dirname, '../../packages/shared/src/theme') },
      { find: /^@orbit\/shared\/theme\/(.*)$/, replacement: path.resolve(__dirname, '../../packages/shared/src/theme/$1') },
      { find: '@orbit/shared/validation', replacement: path.resolve(__dirname, '../../packages/shared/src/validation') },
      { find: /^@orbit\/shared\/validation\/(.*)$/, replacement: path.resolve(__dirname, '../../packages/shared/src/validation/$1') },
      { find: '@orbit/shared/chat', replacement: path.resolve(__dirname, '../../packages/shared/src/chat') },
      { find: /^@orbit\/shared\/chat\/(.*)$/, replacement: path.resolve(__dirname, '../../packages/shared/src/chat/$1') },
      { find: '@orbit/shared/hooks', replacement: path.resolve(__dirname, '../../packages/shared/src/hooks') },
      { find: /^@orbit\/shared\/hooks\/(.*)$/, replacement: path.resolve(__dirname, '../../packages/shared/src/hooks/$1') },
    ],
  },
})
