/** Generated by apps/mobile/scripts/generate-widget-colors.ts. Do not edit. */
export const widgetColorPalette = {
  dark: {
    /** WHY: --bg. */
    bg: '#09090B',
    /** WHY: --bg-card flattened over --bg. */
    card: '#131315',
    /** WHY: --bg-well flattened over --bg. */
    well: '#1D1D1F',
    /** WHY: --hairline-ghost flattened over --bg-card. */
    hairline: '#2B2B2D',
    /** WHY: --fg-1. */
    fg1: '#F4F4F6',
    /** WHY: --fg-2. */
    fg2: '#C9C9CC',
    /** WHY: --fg-3. */
    fg3: '#8F8F93',
    /** WHY: --fg-4. */
    fg4: '#5D5D60',
    /** WHY: --primary. */
    primary: '#C4530F',
    /** WHY: --status-overdue. */
    overdue: '#FE9A00',
  },
  light: {
    /** WHY: --bg. */
    bg: '#FAFAFA',
    /** WHY: --bg-card. */
    card: '#FFFFFF',
    /** WHY: --bg-well flattened over --bg. */
    well: '#F1F1F2',
    /** WHY: --hairline flattened over --bg-card. */
    hairline: '#E6E6E8',
    /** WHY: --fg-1. */
    fg1: '#1A1A1D',
    /** WHY: --fg-2. */
    fg2: '#424247',
    /** WHY: --fg-3. */
    fg3: '#68686D',
    /** WHY: --fg-4. */
    fg4: '#89898D',
    /** WHY: --primary. */
    primary: '#C4530F',
    /** WHY: --status-overdue. */
    overdue: '#946A00',
  },
} as const
