import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url))
const mobileDirectory = path.resolve(scriptDirectory, '..')
const widgetAndroidDirectory = path.join(
  mobileDirectory,
  'modules/orbit-widget/android/src/main',
)

type PaletteKey =
  | 'bg'
  | 'card'
  | 'well'
  | 'hairline'
  | 'fg1'
  | 'fg2'
  | 'fg3'
  | 'fg4'
  | 'primary'
  | 'overdue'
type PaletteEntry = readonly [value: string, token: string]
type Palette = Record<PaletteKey, PaletteEntry>

const COLOR_ROLES = [
  ['background', 'card'],
  ['surface', 'well'],
  ['surfaceGround', 'bg'],
  ['textPrimary', 'fg1'],
  ['textSecondary', 'fg2'],
  ['textMuted', 'fg3'],
  ['border', 'hairline'],
  ['borderMuted', 'hairline'],
  ['overdue', 'overdue'],
  ['streak', 'primary'],
  ['statusEmpty', 'fg4'],
] as const satisfies readonly (readonly [string, PaletteKey])[]

/** The granted canvas palette and its token provenance for generated outputs. */
const PALETTES = {
  dark: {
    bg: ['#09090B', '--bg'],
    card: ['#131315', '--bg-card flattened over --bg'],
    well: ['#1D1D1F', '--bg-well flattened over --bg'],
    hairline: ['#2B2B2D', '--hairline-ghost flattened over --bg-card'],
    fg1: ['#F4F4F6', '--fg-1'],
    fg2: ['#C9C9CC', '--fg-2'],
    fg3: ['#8F8F93', '--fg-3'],
    fg4: ['#5D5D60', '--fg-4'],
    primary: ['#C4530F', '--primary'],
    overdue: ['#FE9A00', '--status-overdue'],
  },
  light: {
    bg: ['#FAFAFA', '--bg'],
    card: ['#FFFFFF', '--bg-card'],
    well: ['#F1F1F2', '--bg-well flattened over --bg'],
    hairline: ['#E6E6E8', '--hairline flattened over --bg-card'],
    fg1: ['#1A1A1D', '--fg-1'],
    fg2: ['#424247', '--fg-2'],
    fg3: ['#68686D', '--fg-3'],
    fg4: ['#89898D', '--fg-4'],
    primary: ['#C4530F', '--primary'],
    overdue: ['#946A00', '--status-overdue'],
  },
} as const satisfies Record<'dark' | 'light', Palette>

const RGB_PATTERN = /^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$/

export function flattenColor(color: string, baseHex: string): string {
  const match = RGB_PATTERN.exec(color)
  if (!match) return color.toUpperCase()

  const overlay = [match[1], match[2], match[3]].map(channel =>
    Number.parseInt(channel ?? '0', 10),
  ) as [number, number, number]
  const alpha = match[4] === undefined ? 1 : Number.parseFloat(match[4])
  const base = baseHex.replace('#', '')
  const blend = (index: 0 | 1 | 2) => {
    const baseChannel = Number.parseInt(base.slice(index * 2, index * 2 + 2), 16)
    return Math.round(overlay[index] * alpha + baseChannel * (1 - alpha))
      .toString(16)
      .padStart(2, '0')
  }

  return `#${blend(0)}${blend(1)}${blend(2)}`.toUpperCase()
}

function generatedTypeScript() {
  const modes = Object.entries(PALETTES).map(([mode, palette]) => {
    const colors = (Object.entries(palette) as [PaletteKey, PaletteEntry][])
      .map(([name, [value, token]]) => `    /** WHY: ${token}. */\n    ${name}: '${value}',`)
      .join('\n')
    return `  ${mode}: {\n${colors}\n  },`
  })

  return `/** Generated by apps/mobile/scripts/generate-widget-colors.ts. Do not edit. */\n` +
    `export const widgetColorPalette = {\n${modes.join('\n')}\n} as const\n`
}

function generatedKotlin() {
  const modes = Object.entries(PALETTES).map(([mode, palette]) => {
    const colors = COLOR_ROLES.map(([key, paletteKey]) => {
      const [value, token] = palette[paletteKey]
      return `        "${key}" to "${value}", // WHY: ${token}.`
    }).join('\n')
    return `    val ${mode} = mapOf(\n${colors}\n    )`
  })

  return `// Generated by apps/mobile/scripts/generate-widget-colors.ts. Do not edit.\n` +
    `package org.useorbit.app.widget\n\n` +
    `internal object WidgetColorFallbacks {\n${modes.join('\n\n')}\n}\n`
}

const RESOURCE_ROLES = [
  ['widget_card', 'card'],
  ['widget_well', 'well'],
  ['widget_hairline', 'hairline'],
  ['widget_fg_1', 'fg1'],
  ['widget_fg_2', 'fg2'],
  ['widget_fg_3', 'fg3'],
  ['widget_fg_4', 'fg4'],
  ['widget_primary', 'primary'],
  ['widget_overdue', 'overdue'],
] as const satisfies readonly (readonly [string, PaletteKey])[]

function generatedXml(mode: keyof typeof PALETTES) {
  const palette = PALETTES[mode]
  const colors = RESOURCE_ROLES.map(([name, paletteKey]) => {
    const [value, token] = palette[paletteKey]
    return `    <!-- WHY: ${token}. -->\n    <color name="${name}">${value}</color>`
  }).join('\n')
  return `<?xml version="1.0" encoding="utf-8"?>\n` +
    `<!-- Generated by apps/mobile/scripts/generate-widget-colors.ts. Do not edit. -->\n` +
    `<resources>\n${colors}\n</resources>\n`
}

export async function generateWidgetColors() {
  const outputs: [string, string][] = [
    [path.join(mobileDirectory, 'lib/widget-colors.generated.ts'), generatedTypeScript()],
    [
      path.join(widgetAndroidDirectory, 'java/org/useorbit/app/widget/WidgetColorFallbacks.generated.kt'),
      generatedKotlin(),
    ],
    [path.join(widgetAndroidDirectory, 'res/values/widget_colors.xml'), generatedXml('light')],
    [path.join(widgetAndroidDirectory, 'res/values-night/widget_colors.xml'), generatedXml('dark')],
  ]

  for (const [outputPath, contents] of outputs) {
    await mkdir(path.dirname(outputPath), { recursive: true })
    await writeFile(outputPath, contents)
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await generateWidgetColors()
}
