export const DEFAULT_HABIT_EMOJI = '✨'

export interface HabitEmojiCategory {
  readonly id: string
  readonly labelKey: string
  readonly searchTerms: string
  readonly emojis: readonly string[]
}

interface HabitEmojiOptionDefinition {
  readonly emoji: string
  readonly keywords: string
}

interface HabitEmojiCategoryDefinition {
  readonly id: string
  readonly labelKey: string
  readonly searchTerms: string
  readonly options: readonly HabitEmojiOptionDefinition[]
}

function emoji(emojiValue: string, keywords: string): HabitEmojiOptionDefinition {
  return { emoji: emojiValue, keywords }
}

const HABIT_EMOJI_CATEGORY_DEFINITIONS: readonly HabitEmojiCategoryDefinition[] = [
  {
    id: 'smileys',
    labelKey: 'habits.form.emojiCategorySmileys',
    searchTerms: 'smileys emotions mood face feeling expression humor expressao emocao sentimento rosto humor',
    options: [
      emoji('😀', 'grinning smile happy alegre sorrir feliz'),
      emoji('😃', 'smile happy excited alegre feliz animado'),
      emoji('😄', 'laugh smile joy risada sorrir alegria'),
      emoji('😁', 'beaming grin teeth sorriso dentes feliz'),
      emoji('😆', 'laugh squint fun rir diversao alegria'),
      emoji('😅', 'sweat smile relief suor alivio sorriso'),
      emoji('😂', 'joy tears laugh rir gargalhada lagrimas'),
      emoji('🤣', 'rolling laugh funny gargalhada engracado'),
      emoji('😊', 'blush smile warm feliz timido sorriso'),
      emoji('😇', 'angel innocent calm anjo inocente calmo'),
      emoji('🙂', 'slight smile calm sorriso leve calmo'),
      emoji('🙃', 'upside down playful brincadeira invertido'),
      emoji('😉', 'wink playful piscar brincalhao'),
      emoji('😍', 'heart eyes love adore apaixonado amor'),
      emoji('🥰', 'love affection hearts carinho amor'),
      emoji('😘', 'kiss love affection beijo amor carinho'),
      emoji('😋', 'yum tasty food gostoso comida'),
      emoji('😛', 'tongue playful lingua brincadeira'),
      emoji('😜', 'wink tongue playful lingua piscar'),
      emoji('🤪', 'goofy silly fun bobo divertido'),
      emoji('🤗', 'hug support embrace abraco apoio'),
      emoji('🤔', 'thinking reflect question pensar refletir duvida'),
      emoji('🫡', 'salute respect discipline saudacao respeito disciplina'),
      emoji('🤩', 'star struck excited estrela empolgado'),
      emoji('🥳', 'party celebrate birthday festa celebrar aniversario'),
      emoji('😎', 'cool confidence sunglasses confiante oculos'),
      emoji('😴', 'sleep tired rest dormir sono descanso'),
      emoji('😌', 'relieved calm peace alivio calma paz'),
      emoji('😮‍💨', 'exhale relief breath breathing respirar alivio folego'),
      emoji('😤', 'determined effort grit determinado esforco'),
      emoji('😭', 'cry tears sad chorar triste lagrimas'),
      emoji('😡', 'angry mad frustrado bravo raiva'),
      emoji('😬', 'grimace awkward tension tensao constrangido'),
      emoji('😐', 'neutral flat neutro serio'),
      emoji('😶', 'silent quiet silence silencio quieto'),
      emoji('🙄', 'eyeroll annoyed irritado impaciente'),
    ],
  },
  {
    id: 'body',
    labelKey: 'habits.form.emojiCategoryBody',
    searchTerms: 'people body hands health anatomy social connection pessoas corpo maos saude anatomia social conexao',
    options: [
      emoji('👋', 'wave hello goodbye acenar ola tchau'),
      emoji('👏', 'clap applause praise aplaudir parabens'),
      emoji('🙌', 'raised hands celebrate praise maos celebrar comemorar'),
      emoji('🙏', 'pray thanks gratitude prayer rezar obrigado gratidao'),
      emoji('💪', 'muscle strength strong workout musculo forca forte treino'),
      emoji('🤝', 'handshake agreement deal aperto de mao acordo'),
      emoji('👍', 'thumbs up approve yes positivo aprovar sim'),
      emoji('👎', 'thumbs down disapprove no negativo reprovar nao'),
      emoji('✌️', 'peace victory two paz vitoria dois'),
      emoji('🤞', 'fingers crossed hope sorte torcer esperanca'),
      emoji('🫶', 'heart hands care love maos coracao carinho amor'),
      emoji('🤟', 'love you gesture rock gesto amor rock'),
      emoji('👀', 'eyes see watch olhar ver observar olhos'),
      emoji('🧠', 'brain mind thinking mente cerebro pensar'),
      emoji('🫀', 'heart organ cardio coracao orgao cardio'),
      emoji('🫁', 'lungs breath breathing pulmoes respirar folego'),
      emoji('🦷', 'tooth dentist dental dente dentista'),
      emoji('🦴', 'bone skeleton strength osso esqueleto'),
      emoji('👣', 'footprints steps walk pegadas passos caminhar'),
      emoji('🗣️', 'speak voice talk falar voz conversa'),
      emoji('👤', 'person profile user pessoa perfil usuario'),
      emoji('👥', 'people group community pessoas grupo comunidade'),
      emoji('🧍', 'stand standing posture ficar em pe postura'),
      emoji('🧎', 'kneel kneeling prayer ajoelhar joelho'),
      emoji('💃', 'dance dancer salsa dancar danca'),
      emoji('🕺', 'dance dancer disco dancar danca'),
      emoji('🧑‍💻', 'technologist computer work code computador tecnologia programar'),
      emoji('🧑‍🍳', 'cook chef cooking cozinhar chef'),
      emoji('🧑‍🎨', 'artist art paint artista arte pintar'),
      emoji('🧑‍🏫', 'teacher teach class professor aula ensinar'),
      emoji('🧑‍🔬', 'scientist science lab cientista ciencia laboratorio'),
      emoji('🧑‍⚕️', 'health worker doctor nurse medico enfermeiro saude'),
    ],
  },
  {
    id: 'wellness',
    labelKey: 'habits.form.emojiCategoryWellness',
    searchTerms: 'wellness fitness exercise gym yoga meditate medicine hygiene self care bem estar exercicio academia ioga meditar remedio higiene autocuidado',
    options: [
      emoji('🏃', 'run running cardio exercise correr corrida cardio exercicio'),
      emoji('🏃‍♀️', 'woman running run cardio corredora correr corrida cardio'),
      emoji('🏃‍♂️', 'man running run cardio corredor correr corrida cardio'),
      emoji('🚶', 'walk walking steps stroll caminhar caminhada passos'),
      emoji('🚶‍♀️', 'woman walking steps caminhada caminhar passos'),
      emoji('🚶‍♂️', 'man walking steps caminhada caminhar passos'),
      emoji('🧘', 'meditate yoga mindfulness calm meditar ioga atencao plena calma'),
      emoji('🧘‍♀️', 'woman meditating yoga mindfulness meditar ioga calma'),
      emoji('🧘‍♂️', 'man meditating yoga mindfulness meditar ioga calma'),
      emoji('🏋️‍♀️', 'woman lifting weights gym strength musculacao academia forca'),
      emoji('🏋️‍♂️', 'man lifting weights gym strength musculacao academia forca'),
      emoji('🤸', 'cartwheel gymnastics mobility ginastica mobilidade'),
      emoji('🤸‍♀️', 'woman cartwheel gymnastics ginastica mobilidade'),
      emoji('🤸‍♂️', 'man cartwheel gymnastics ginastica mobilidade'),
      emoji('🚴', 'bike cycling bicycle pedalar bicicleta ciclismo'),
      emoji('🚴‍♀️', 'woman cycling bike bicicleta pedalar ciclismo'),
      emoji('🚴‍♂️', 'man cycling bike bicicleta pedalar ciclismo'),
      emoji('🏊', 'swim swimming pool nadar natacao piscina'),
      emoji('🏊‍♀️', 'woman swimming pool nadar natacao piscina'),
      emoji('🏊‍♂️', 'man swimming pool nadar natacao piscina'),
      emoji('🧗', 'climb climbing boulder escalada escalar'),
      emoji('🧗‍♀️', 'woman climbing escalada escalar'),
      emoji('🧗‍♂️', 'man climbing escalada escalar'),
      emoji('🛀', 'bath relax self care banho relaxar autocuidado'),
      emoji('🛌', 'bed sleep rest cama dormir descanso'),
      emoji('💧', 'water drop hydrate agua gota hidratacao beber'),
      emoji('🥛', 'milk glass dairy leite copo calcio'),
      emoji('💊', 'pill medicine medication remedio medicamento comprimido'),
      emoji('🩹', 'bandage healing first aid curativo cicatrizar primeiros socorros'),
      emoji('🩺', 'stethoscope doctor checkup estetoscopio medico consulta'),
      emoji('🧴', 'lotion sunscreen skincare protetor solar creme pele'),
      emoji('🪥', 'toothbrush brush teeth escova dente escovar'),
      emoji('🧼', 'soap clean wash sabonete lavar limpeza'),
      emoji('🧽', 'sponge scrub clean esponja limpar esfregar'),
      emoji('🫧', 'bubbles soap bath bolhas espuma banho'),
      emoji('🕯️', 'candle calm ritual vela calma ritual'),
      emoji('🪷', 'lotus meditation calm lotus meditar calma'),
      emoji('🚭', 'no smoking quit smoke parar de fumar cigarro proibido'),
      emoji('🧊', 'ice cold shower cold plunge gelo banho frio'),
    ],
  },
  {
    id: 'animals',
    labelKey: 'habits.form.emojiCategoryAnimals',
    searchTerms: 'animals pets wildlife creature bichos animais pets animal estimacao fauna',
    options: [
      emoji('🐶', 'dog puppy pet cachorro cao filhote animal estimacao'),
      emoji('🐕', 'dog pet cachorro cao animal estimacao'),
      emoji('🦮', 'guide dog service dog cao guia cachorro servico'),
      emoji('🐱', 'cat kitten pet gato gata filhote animal estimacao'),
      emoji('🐈', 'cat pet gato gata animal estimacao'),
      emoji('🐭', 'mouse rat rato camundongo'),
      emoji('🐹', 'hamster pet hamster animal estimacao'),
      emoji('🐰', 'rabbit bunny coelho'),
      emoji('🦊', 'fox raposa'),
      emoji('🐻', 'bear urso'),
      emoji('🐼', 'panda panda urso'),
      emoji('🐨', 'koala coala'),
      emoji('🐯', 'tiger tigre'),
      emoji('🦁', 'lion leao'),
      emoji('🐮', 'cow vaca boi'),
      emoji('🐷', 'pig porco porca'),
      emoji('🐸', 'frog sapo ra'),
      emoji('🐵', 'monkey macaco'),
      emoji('🐔', 'chicken hen galinha frango'),
      emoji('🐦', 'bird passaro ave'),
      emoji('🐧', 'penguin pinguim'),
      emoji('🦆', 'duck pato'),
      emoji('🦅', 'eagle aguia'),
      emoji('🦉', 'owl coruja'),
      emoji('🦇', 'bat morcego'),
      emoji('🐺', 'wolf lobo'),
      emoji('🐴', 'horse cavalo'),
      emoji('🦄', 'unicorn unicornio'),
      emoji('🐝', 'bee abelha'),
      emoji('🦋', 'butterfly borboleta'),
      emoji('🐛', 'bug worm inseto lagarta verme'),
      emoji('🐌', 'snail caracol lesma'),
      emoji('🐞', 'ladybug lady beetle joaninha'),
      emoji('🐢', 'turtle tortoise tartaruga'),
      emoji('🐍', 'snake cobra serpente'),
      emoji('🦎', 'lizard lagarto'),
      emoji('🐠', 'fish tropical peixe'),
      emoji('🐟', 'fish peixe'),
      emoji('🐬', 'dolphin golfinho'),
      emoji('🐳', 'whale baleia'),
    ],
  },
  {
    id: 'nature',
    labelKey: 'habits.form.emojiCategoryNature',
    searchTerms: 'nature plants weather outdoors garden growth sun moon water fire earth natureza plantas clima ar livre jardim crescimento sol lua agua fogo terra',
    options: [
      emoji('🌱', 'seedling sprout growth plant broto muda crescimento planta'),
      emoji('🌿', 'herb plant leaf erva planta folha'),
      emoji('☘️', 'shamrock clover trevo sorte'),
      emoji('🍀', 'four leaf clover luck trevo sorte'),
      emoji('🪴', 'potted plant houseplant vaso planta'),
      emoji('🌵', 'cactus desert cacto deserto'),
      emoji('🌴', 'palm tree tropical coqueiro palmeira tropical'),
      emoji('🌳', 'tree deciduous arvore'),
      emoji('🌲', 'evergreen tree pine pinheiro arvore'),
      emoji('🌷', 'tulip flower tulipa flor'),
      emoji('🌸', 'blossom flower flor cerejeira'),
      emoji('🌼', 'flower daisy flor margarida'),
      emoji('🌻', 'sunflower flower girassol flor'),
      emoji('🍄', 'mushroom fungus cogumelo fungo'),
      emoji('🌞', 'sun face sunny sol ensolarado'),
      emoji('☀️', 'sun sunny daylight sol dia'),
      emoji('🌙', 'moon night lua noite'),
      emoji('⭐️', 'star estrela'),
      emoji('🌟', 'glowing star estrela brilho'),
      emoji('✨', 'sparkles magic shine brilho magia especial'),
      emoji('🌈', 'rainbow color arco iris cor'),
      emoji('🔥', 'fire flame heat fogo chama calor'),
      emoji('💧', 'water drop agua gota hidratacao'),
      emoji('🌊', 'wave ocean sea onda mar oceano'),
      emoji('❄️', 'snowflake cold ice neve frio gelo'),
      emoji('⚡️', 'lightning energy thunder raio energia trovao'),
      emoji('🌍', 'earth globe world terra mundo planeta'),
      emoji('🌕', 'full moon lua cheia noite'),
      emoji('🌧️', 'rain cloud rainy chuva nuvem chuvoso'),
      emoji('☁️', 'cloud cloudy nuvem nublado'),
    ],
  },
  {
    id: 'food',
    labelKey: 'habits.form.emojiCategoryFood',
    searchTerms: 'food drink nutrition diet meal cook coffee tea fruit vegetable hydrate water protein comida bebida nutricao dieta refeicao cozinhar cafe cha fruta vegetal proteina agua',
    options: [
      emoji('🍎', 'apple fruit healthy maca fruta saudavel'),
      emoji('🍌', 'banana fruit potassium banana fruta potassio'),
      emoji('🍊', 'orange fruit citrus laranja fruta citrico'),
      emoji('🍋', 'lemon citrus limao citrico'),
      emoji('🍓', 'strawberry berry morango fruta'),
      emoji('🫐', 'blueberries berry mirtilo fruta'),
      emoji('🍇', 'grapes fruit uva fruta'),
      emoji('🍉', 'watermelon fruit melancia fruta'),
      emoji('🍍', 'pineapple fruit abacaxi fruta'),
      emoji('🥝', 'kiwi fruit kiwi fruta'),
      emoji('🥑', 'avocado fruit abacate gordura boa'),
      emoji('🥦', 'broccoli vegetable brocolis vegetal verdura'),
      emoji('🥕', 'carrot vegetable cenoura vegetal'),
      emoji('🌽', 'corn vegetable milho vegetal'),
      emoji('🥗', 'salad healthy meal salada saudavel refeicao'),
      emoji('🍞', 'bread toast pao torrada'),
      emoji('🥚', 'egg protein ovo proteina'),
      emoji('🍳', 'cooking egg breakfast cozinhar ovo cafe manha'),
      emoji('🥘', 'pan food meal panela comida refeicao'),
      emoji('🍲', 'stew soup bowl ensopado sopa tigela'),
      emoji('🍜', 'noodles ramen soup macarrao lamem sopa'),
      emoji('🍣', 'sushi fish sushi peixe'),
      emoji('🍛', 'curry rice curry arroz'),
      emoji('🍝', 'spaghetti pasta macarrao massa'),
      emoji('🥣', 'bowl cereal oatmeal tigela cereal aveia'),
      emoji('🥜', 'peanuts nuts protein amendoim castanhas proteina'),
      emoji('🍯', 'honey sweet mel doce'),
      emoji('☕️', 'coffee caffeine morning cafe cafeina manha'),
      emoji('🍵', 'tea matcha cha verde matcha'),
      emoji('🧃', 'juice box suco caixinha'),
      emoji('🥤', 'cup straw drink copo canudo bebida'),
      emoji('🧋', 'bubble tea boba cha perolas'),
      emoji('🍼', 'baby bottle leite mamadeira'),
      emoji('🍽️', 'plate meal dinner prato refeicao jantar'),
      emoji('🥄', 'spoon colher'),
      emoji('🔪', 'knife cook prep faca cozinhar preparo'),
    ],
  },
  {
    id: 'activities',
    labelKey: 'habits.form.emojiCategoryActivities',
    searchTerms: 'activities sports hobbies creative music game art practice train play atividades esportes hobbies criativo musica jogo arte praticar treinar brincar',
    options: [
      emoji('⚽️', 'soccer football bola futebol esporte'),
      emoji('🏀', 'basketball sport basquete esporte'),
      emoji('🏈', 'football american sport futebol americano esporte'),
      emoji('⚾️', 'baseball sport beisebol esporte'),
      emoji('🎾', 'tennis sport tenis esporte'),
      emoji('🏐', 'volleyball sport volei voleibol esporte'),
      emoji('🏓', 'ping pong table tennis tenis mesa esporte'),
      emoji('🏸', 'badminton sport badminton esporte'),
      emoji('🥊', 'boxing glove fight boxe luta'),
      emoji('🥋', 'martial arts karate judo artes marciais luta'),
      emoji('🛹', 'skateboard skate skateboarding skate esporte'),
      emoji('⛸️', 'ice skate skating patins gelo patinacao'),
      emoji('🎯', 'target goal aim alvo meta foco'),
      emoji('🎮', 'video game controller jogo videogame controle'),
      emoji('🎲', 'dice board game dado jogo tabuleiro'),
      emoji('🧩', 'puzzle piece quebra cabeca peca'),
      emoji('♟️', 'chess strategy xadrez estrategia'),
      emoji('🎨', 'palette art paint paleta arte pintura'),
      emoji('🖌️', 'paintbrush art pincel arte pintar'),
      emoji('✏️', 'pencil draw write lapis desenhar escrever'),
      emoji('🎸', 'guitar music violao guitarra musica'),
      emoji('🎹', 'piano keyboard music piano teclado musica'),
      emoji('🥁', 'drum music bateria tambor musica'),
      emoji('🎧', 'headphones music audio fone musica audio'),
      emoji('🎤', 'microphone sing mic microfone cantar'),
      emoji('🎬', 'movie film cinema filme cinema'),
      emoji('📷', 'camera photo fotografia camera foto'),
      emoji('📹', 'video camera film camera video filmar'),
      emoji('🧶', 'yarn knitting crochet la tricotar croche'),
      emoji('🪡', 'needle sewing costura agulha costurar'),
      emoji('🎣', 'fishing fish pesca pescar peixe'),
      emoji('⛳️', 'golf flag golfe bandeira'),
      emoji('🏆', 'trophy prize win trofeu premio vencer'),
      emoji('🥇', 'gold medal first medalha ouro primeiro'),
      emoji('🎟️', 'ticket event ingresso evento'),
      emoji('🎭', 'theater drama masks teatro mascaras'),
    ],
  },
  {
    id: 'work',
    labelKey: 'habits.form.emojiCategoryWork',
    searchTerms: 'work study school reading writing plan calendar productivity focus admin finance learn trabalho estudo escola leitura escrita planejar calendario produtividade foco administrativo financas aprender',
    options: [
      emoji('📚', 'books reading study livros leitura estudar'),
      emoji('📖', 'open book read livro aberto ler leitura'),
      emoji('✍️', 'writing hand journal write escrever diario anotacao'),
      emoji('📝', 'memo notes tasks nota anotacoes tarefas'),
      emoji('📓', 'notebook notes caderno anotacoes'),
      emoji('📔', 'notebook journal caderno diario'),
      emoji('📒', 'ledger notebook caderno registro'),
      emoji('📕', 'red book livro vermelho leitura'),
      emoji('📗', 'green book livro verde leitura'),
      emoji('📘', 'blue book livro azul leitura'),
      emoji('📙', 'orange book livro laranja leitura'),
      emoji('💻', 'laptop computer code notebook computador programar'),
      emoji('⌨️', 'keyboard typing teclado digitar'),
      emoji('🖥️', 'desktop computer monitor computador monitor'),
      emoji('📱', 'phone mobile celular telefone'),
      emoji('🗓️', 'spiral calendar schedule calendario agenda'),
      emoji('📅', 'calendar date schedule calendario data agenda'),
      emoji('⏰', 'alarm clock time relogio alarme tempo'),
      emoji('⏳', 'hourglass time waiting ampulheta tempo esperar'),
      emoji('⌛️', 'hourglass done time ampulheta tempo'),
      emoji('📌', 'pushpin pin reminder alfinete lembrete'),
      emoji('📎', 'paperclip attach clipe anexar'),
      emoji('✂️', 'scissors cut tesoura cortar'),
      emoji('📁', 'folder file pasta arquivo'),
      emoji('📂', 'open folder file pasta aberta arquivo'),
      emoji('📊', 'bar chart data grafico barras dados'),
      emoji('📈', 'chart increasing growth grafico crescimento subir'),
      emoji('📉', 'chart decreasing decline grafico queda descer'),
      emoji('🔍', 'search magnifier find busca pesquisar lupa'),
      emoji('💡', 'idea light bulb ideia lampada'),
      emoji('🧪', 'test tube experiment tubo ensaio experimento'),
      emoji('🧮', 'abacus math calculate abaco matematica calcular'),
      emoji('🧾', 'receipt bill recibo conta comprovante'),
      emoji('💰', 'money bag budget dinheiro orcamento financas'),
      emoji('💳', 'credit card payment cartao credito pagamento'),
      emoji('🏦', 'bank finance banco financas'),
    ],
  },
  {
    id: 'home',
    labelKey: 'habits.form.emojiCategoryHome',
    searchTerms: 'home chores clean organize laundry shopping repair car family house routine casa tarefas limpeza organizar lavanderia compras conserto carro familia rotina',
    options: [
      emoji('🏠', 'home house casa lar'),
      emoji('🏡', 'house garden home casa jardim lar'),
      emoji('🧹', 'broom sweep clean vassoura varrer limpeza'),
      emoji('🧺', 'basket laundry cesta roupa lavanderia'),
      emoji('🧼', 'soap clean wash sabonete lavar limpeza'),
      emoji('🛁', 'bathtub bath banheira banho'),
      emoji('🛏️', 'bed bedroom sleep cama quarto dormir'),
      emoji('🛋️', 'couch sofa sofa sala'),
      emoji('🍽️', 'dishes plate meal louca prato refeicao'),
      emoji('🧽', 'sponge scrub clean esponja limpar esfregar'),
      emoji('🪣', 'bucket clean balde limpeza'),
      emoji('🛒', 'cart shopping groceries carrinho compras mercado'),
      emoji('🧾', 'receipt bill recibo conta comprovante'),
      emoji('🔑', 'key keys chave chaves'),
      emoji('🚗', 'car drive carro dirigir'),
      emoji('🚙', 'suv car vehicle carro veiculo'),
      emoji('📦', 'package box caixa pacote entrega'),
      emoji('🧰', 'toolbox repair tools caixa ferramentas conserto'),
      emoji('🔧', 'wrench repair tool chave inglesa consertar ferramenta'),
      emoji('🪛', 'screwdriver repair tool chave fenda conserto'),
      emoji('🔨', 'hammer build repair martelo construir conserto'),
      emoji('🧱', 'brick build tijolo construir'),
      emoji('🪜', 'ladder repair escada conserto'),
      emoji('🧯', 'fire extinguisher safety extintor seguranca'),
      emoji('🪫', 'low battery bateria fraca'),
      emoji('🔋', 'battery energy bateria energia'),
      emoji('💡', 'light bulb idea lampada luz ideia'),
      emoji('🧸', 'teddy bear toy ursinho brinquedo'),
      emoji('🎁', 'gift present presente'),
      emoji('🪴', 'potted plant houseplant planta vaso'),
      emoji('🗑️', 'trash garbage lixo lixeira'),
      emoji('🚿', 'shower banho chuveiro'),
      emoji('🧻', 'toilet paper papel higienico'),
      emoji('🪞', 'mirror espelho'),
      emoji('🚪', 'door porta'),
      emoji('🪟', 'window janela'),
    ],
  },
  {
    id: 'travel',
    labelKey: 'habits.form.emojiCategoryTravel',
    searchTerms: 'travel commute outside places trip walk drive bike train plane map direction viagem deslocamento fora lugares passeio caminhar dirigir bicicleta trem aviao mapa direcao',
    options: [
      emoji('🚶', 'walk walking commute caminhar caminhada deslocamento'),
      emoji('🚗', 'car drive commute carro dirigir deslocamento'),
      emoji('🚕', 'taxi cab taxi transporte'),
      emoji('🚌', 'bus commute onibus transporte'),
      emoji('🚆', 'train trem transporte'),
      emoji('🚇', 'metro subway metro trem'),
      emoji('✈️', 'plane flight travel aviao voo viagem'),
      emoji('🚲', 'bicycle bike cycling bicicleta pedalar'),
      emoji('🛴', 'scooter patinete'),
      emoji('⛵️', 'sailboat boat barco veleiro'),
      emoji('🚢', 'ship cruise navio cruzeiro'),
      emoji('🏕️', 'camping tent acampar barraca'),
      emoji('🏖️', 'beach umbrella praia guarda sol'),
      emoji('🏔️', 'mountain snowy montanha neve'),
      emoji('🏙️', 'city skyline cidade predios'),
      emoji('🌅', 'sunrise dawn nascer do sol amanhecer'),
      emoji('🌄', 'sunrise mountains nascer do sol montanhas'),
      emoji('🗺️', 'map travel mapa viagem'),
      emoji('🧭', 'compass direction bussola direcao'),
      emoji('🎒', 'backpack bag mochila'),
      emoji('🧳', 'luggage suitcase mala bagagem'),
      emoji('🎫', 'ticket pass passagem ingresso'),
      emoji('🛤️', 'railway track trilho trem'),
      emoji('🛣️', 'motorway road estrada rodovia'),
      emoji('⛽️', 'fuel gas pump gasolina combustivel posto'),
      emoji('🚦', 'traffic light semaforo transito'),
      emoji('🏟️', 'stadium estadio'),
      emoji('🏛️', 'classical building museum courthouse predio museu tribunal'),
      emoji('⛩️', 'shrine gate santuario portal'),
      emoji('🕌', 'mosque mesquita'),
      emoji('⛪️', 'church igreja'),
      emoji('🛍️', 'shopping bags compras sacolas'),
      emoji('🏪', 'convenience store loja mercado'),
      emoji('🏥', 'hospital hospital saude'),
      emoji('🏫', 'school escola'),
      emoji('🏢', 'office building predio escritorio'),
    ],
  },
  {
    id: 'symbols',
    labelKey: 'habits.form.emojiCategorySymbols',
    searchTerms: 'symbols status color heart check star fire goal alert stop yes no priority simbolos status cor coracao marca estrela fogo meta alerta parar sim nao prioridade',
    options: [
      emoji('❤️', 'red heart love care coracao vermelho amor cuidado'),
      emoji('🧡', 'orange heart love coracao laranja amor'),
      emoji('💛', 'yellow heart love coracao amarelo amor'),
      emoji('💚', 'green heart love coracao verde amor'),
      emoji('💙', 'blue heart love coracao azul amor'),
      emoji('💜', 'purple heart love coracao roxo amor'),
      emoji('🖤', 'black heart love coracao preto amor'),
      emoji('🤍', 'white heart love coracao branco amor'),
      emoji('🤎', 'brown heart love coracao marrom amor'),
      emoji('💔', 'broken heart heartbreak coracao partido'),
      emoji('💯', 'hundred perfect score cem perfeito nota'),
      emoji('✅', 'check mark done complete sim concluido feito'),
      emoji('☑️', 'checkbox check done caixa marcada concluido'),
      emoji('✔️', 'check mark tick certo marca'),
      emoji('❌', 'cross mark no wrong x errado nao'),
      emoji('⭕️', 'circle ok zero circulo correto'),
      emoji('🚫', 'prohibited banned no proibido bloqueado nao'),
      emoji('⚠️', 'warning alert caution aviso alerta cuidado'),
      emoji('🔴', 'red circle vermelho circulo'),
      emoji('🟠', 'orange circle laranja circulo'),
      emoji('🟡', 'yellow circle amarelo circulo'),
      emoji('🟢', 'green circle verde circulo'),
      emoji('🔵', 'blue circle azul circulo'),
      emoji('🟣', 'purple circle roxo circulo'),
      emoji('⚪️', 'white circle branco circulo'),
      emoji('⚫️', 'black circle preto circulo'),
      emoji('🟤', 'brown circle marrom circulo'),
      emoji('⭐️', 'star favorite estrela favorito'),
      emoji('🌟', 'glowing star sparkle estrela brilho'),
      emoji('✨', 'sparkles magic default fresh start brilho magia padrao recomeço recomeco'),
      emoji('🔥', 'fire streak priority fogo sequencia prioridade'),
      emoji('🎯', 'target goal focus alvo meta foco'),
      emoji('📍', 'pin location marker local marcador pino'),
      emoji('🔔', 'bell reminder notification sino lembrete notificacao'),
      emoji('🔒', 'locked private secure trancado privado seguro'),
      emoji('🔓', 'unlocked open destrancado aberto'),
    ],
  },
] as const

export const HABIT_EMOJI_CATEGORIES: readonly HabitEmojiCategory[] = HABIT_EMOJI_CATEGORY_DEFINITIONS.map(
  (category) => ({
    id: category.id,
    labelKey: category.labelKey,
    searchTerms: category.searchTerms,
    emojis: category.options.map((option) => option.emoji),
  }),
)

export const HABIT_EMOJI_OPTIONS: readonly string[] = Array.from(
  new Set(HABIT_EMOJI_CATEGORIES.flatMap((category) => category.emojis)),
)

export type HabitEmojiOption = string

const HABIT_EMOJI_SEARCH_TERMS = new Map(
  HABIT_EMOJI_CATEGORY_DEFINITIONS.flatMap((category) => (
    category.options.map((option) => [option.emoji, option.keywords] as const)
  )),
)

function normalizeEmojiSearch(value: string): string {
  return value
    .trim()
    .toLocaleLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
}

function emojiMatchesSearch(emojiValue: string, category: HabitEmojiCategory, query: string): boolean {
  const keywords = HABIT_EMOJI_SEARCH_TERMS.get(emojiValue) ?? ''
  const searchableText = normalizeEmojiSearch(
    `${emojiValue} ${category.id} ${category.searchTerms} ${keywords}`,
  )
  return searchableText.includes(query)
}

export function filterHabitEmojiCategories(query: string): readonly HabitEmojiCategory[] {
  const normalizedQuery = normalizeEmojiSearch(query)
  if (!normalizedQuery) return HABIT_EMOJI_CATEGORIES

  return HABIT_EMOJI_CATEGORIES
    .map((category) => ({
      ...category,
      emojis: category.emojis.filter((emojiValue) => emojiMatchesSearch(emojiValue, category, normalizedQuery)),
    }))
    .filter((category) => category.emojis.length > 0)
}

export function resolveHabitEmoji(emoji: string | null | undefined): string {
  const normalized = emoji?.trim()
  return normalized && normalized.length > 0 ? normalized : DEFAULT_HABIT_EMOJI
}
