import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  container: { flex: 1 },
  scrollContent: {
    paddingTop: 8,
    paddingBottom: 40,
  },
  bottomSpace: { height: 24 },
  heroTitle: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 24,
    lineHeight: 31,
    letterSpacing: -0.24,
    marginHorizontal: 20,
    marginBottom: 22,
  },
  trialStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 20,
    marginBottom: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
  },
  trialStripText: {
    flex: 1,
    fontFamily: 'Rubik_400Regular',
    fontSize: 13,
  },
  card: {
    marginHorizontal: 20,
    marginBottom: 12,
    borderRadius: 18,
    borderWidth: 1,
    paddingVertical: 16,
    paddingHorizontal: 18,
  },
  cardLabel: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
  },
  cardValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 3,
  },
  cardValue: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 17,
  },
  cardMeta: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 13,
    fontVariant: ['tabular-nums'],
    marginTop: 8,
  },
  badBadge: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  badBadgeText: {
    fontFamily: 'Rubik_600SemiBold',
    fontSize: 10.5,
    letterSpacing: 0.63,
    textTransform: 'uppercase',
  },
  usageRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 8,
    marginBottom: 10,
  },
  usageLabel: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 15,
  },
  usageValue: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 13,
    fontVariant: ['tabular-nums'],
  },
  proPanel: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 26,
    paddingBottom: 16,
    gap: 10,
  },
  proPanelTitle: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 24,
    letterSpacing: -0.24,
    lineHeight: 31,
    marginTop: 8,
    textAlign: 'center',
  },
  proPanelHint: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    lineHeight: 21,
    maxWidth: 320,
    textAlign: 'center',
  },
  expiredCard: {
    marginBottom: 16,
    paddingVertical: 18,
  },
  expiredHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  expiredTitle: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 16,
  },
  expiredSub: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    marginTop: 6,
  },
  expiredList: {
    gap: 9,
    marginTop: 12,
  },
  featureCheckRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  featureCheckText: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    flexShrink: 1,
  },
  planGroup: {
    paddingHorizontal: 20,
    gap: 14,
  },
  actionPad: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 4,
    gap: 12,
    alignItems: 'center',
  },
  couponRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  couponNote: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 12,
  },
  renewalNote: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    marginHorizontal: 4,
  },
  restoreLink: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 13,
  },
  actionChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingVertical: 9,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pressedScale: {
    transform: [{ scale: 0.96 }],
  },
  iconWell: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  link: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 13,
  },
  padBlock: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 8,
    alignItems: 'center',
  },
  noticeText: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    textAlign: 'center',
  },
  mutedMeta: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 12,
    textAlign: 'center',
  },
  centerMuted: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  errorText: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 12,
    textAlign: 'center',
  },
  invoiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    gap: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  invoiceIconSlot: {
    width: 26,
    alignItems: 'center',
    flexShrink: 0,
  },
  invoiceMeta: { flex: 1 },
  invoiceDate: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    marginTop: 3,
  },
  invoiceStatus: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 11,
    letterSpacing: 0.44,
    textTransform: 'uppercase',
    flexShrink: 0,
  },
  invoiceAmount: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 16,
  },
  comparisonPad: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 20,
    paddingTop: 28,
  },
  planColumn: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    paddingVertical: 16,
    paddingHorizontal: 14,
  },
  planColumnPro: {
    borderWidth: 1.5,
  },
  planColumnHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 26,
    marginBottom: 14,
  },
  planColumnTitle: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 16,
    letterSpacing: -0.16,
  },
  planColumnBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  planColumnBadgeText: {
    fontFamily: 'Rubik_600SemiBold',
    fontSize: 9.5,
    letterSpacing: 0.48,
    textTransform: 'uppercase',
  },
  planFeatureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    minHeight: 34,
  },
  planFeatureText: {
    flex: 1,
    fontFamily: 'Rubik_400Regular',
    fontSize: 12.5,
    lineHeight: 17,
  },
})
