import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  allowanceSection: {
    gap: 12,
    marginTop: 32,
    paddingHorizontal: 16,
  },
  allowanceCard: {
    alignItems: 'stretch',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 16,
    padding: 16,
  },
  allowanceColumn: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  allowanceDivider: {
    width: 1,
  },
  allowanceLabel: {
    fontFamily: 'RobotoMono_400Regular',
    fontSize: 12,
    letterSpacing: 0.48,
  },
  allowanceAmount: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 34,
    fontVariant: ['tabular-nums'],
    letterSpacing: -0.68,
    lineHeight: 36,
  },
  allowancePerDay: {
    fontFamily: 'Geist_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  allowanceNote: {
    fontFamily: 'Geist_400Regular',
    fontSize: 14,
    lineHeight: 22,
  },
  outcomes: {
    gap: 12,
    marginTop: 32,
    paddingHorizontal: 16,
  },
  outcomeRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  outcomeIcon: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    marginTop: 4,
    width: 24,
  },
  outcomeCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  outcomeTitle: {
    fontFamily: 'Geist_500Medium',
    fontSize: 17,
    lineHeight: 24,
  },
  outcomeBody: {
    fontFamily: 'Geist_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  planState: {
    gap: 12,
    marginTop: 32,
    paddingHorizontal: 16,
  },
  planChoices: {
    gap: 12,
  },
  safe: { flex: 1 },
  container: { flex: 1 },
  scrollContent: {
    paddingTop: 8,
    paddingBottom: 40,
  },
  bottomSpace: { height: 24 },
  convertEyebrow: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 12,
    letterSpacing: 0.96,
    textTransform: 'uppercase',
    marginHorizontal: 20,
  },
  convertHeading: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 34,
    lineHeight: 39,
    letterSpacing: -0.34,
    marginHorizontal: 20,
    marginTop: 6,
  },
  convertPromise: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    lineHeight: 21,
    marginHorizontal: 20,
    marginTop: 10,
  },
  convertTrust: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 12,
    lineHeight: 18,
    marginHorizontal: 20,
    marginTop: 10,
  },
  card: {
    marginHorizontal: 20,
    marginBottom: 12,
    borderRadius: 18,
    borderWidth: 1,
    paddingVertical: 16,
    paddingHorizontal: 18,
  },
  cardLabel: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
  },
  cardValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  cardValue: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 17,
  },
  cardMeta: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 13,
    fontVariant: ['tabular-nums'],
    marginTop: 8,
  },
  usageRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 8,
    marginBottom: 10,
  },
  usageLabel: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 15,
  },
  usageValue: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 13,
    fontVariant: ['tabular-nums'],
  },
  proPanel: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 26,
    paddingBottom: 16,
    gap: 10,
  },
  proPanelTitle: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 24,
    letterSpacing: -0.24,
    lineHeight: 31,
    marginTop: 8,
    textAlign: 'center',
  },
  proPanelHint: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    lineHeight: 21,
    maxWidth: 320,
    textAlign: 'center',
  },
  freeLink: {
    alignSelf: 'flex-start',
    justifyContent: 'center',
    minHeight: 44,
  },
  freeLinkText: {
    fontFamily: 'Geist_400Regular',
    fontSize: 16,
    lineHeight: 24,
    textDecorationLine: 'underline',
  },
  marqueePad: {
    paddingHorizontal: 20,
    paddingTop: 24,
    gap: 14,
  },
  marqueeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  marqueeIcon: {
    width: 26,
    alignItems: 'center',
  },
  marqueeText: {
    flex: 1,
    fontFamily: 'Rubik_400Regular',
    fontSize: 15,
  },
  planGroup: {
    paddingHorizontal: 16,
    gap: 16,
    marginTop: 32,
  },
  tierCard: {
    borderRadius: 20,
    gap: 8,
    padding: 24,
  },
  tierHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  tierName: {
    flex: 1,
    fontFamily: 'Geist_500Medium',
    fontSize: 17,
    lineHeight: 22,
    minWidth: 0,
  },
  tierPrice: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 28,
    fontVariant: ['tabular-nums'],
    letterSpacing: -0.56,
    lineHeight: 32,
  },
  tierPeriod: {
    fontFamily: 'Geist_400Regular',
    fontSize: 16,
  },
  tierHero: {
    fontFamily: 'Geist_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  tierSecond: {
    fontFamily: 'RobotoMono_400Regular',
    fontSize: 12,
    fontVariant: ['tabular-nums'],
    lineHeight: 18,
  },
  tierCoupon: {
    fontFamily: 'Geist_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  tierAction: {
    paddingTop: 8,
  },
  actionPad: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 4,
    gap: 12,
    alignItems: 'center',
  },
  couponRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  couponNote: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 12,
  },
  renewalNote: {
    fontFamily: 'Geist_400Regular',
    fontSize: 14,
    lineHeight: 22,
  },
  handoffNote: {
    fontFamily: 'Geist_400Regular',
    fontSize: 14,
    lineHeight: 22,
  },
  reassurance: {
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 16,
    paddingHorizontal: 16,
  },
  reassurancePrimary: {
    fontFamily: 'Geist_400Regular',
    fontSize: 14,
    lineHeight: 22,
  },
  restoreLink: {
    fontFamily: 'Geist_500Medium',
    fontSize: 14,
  },
  restoreAction: {
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 24,
    minHeight: 44,
  },
  pressedScale: {
    transform: [{ scale: 0.96 }],
  },
  iconWell: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  link: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 13,
  },
  padBlock: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 8,
    alignItems: 'center',
  },
  noticeText: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    textAlign: 'center',
  },
  centerMuted: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  errorText: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 12,
    textAlign: 'center',
  },
  invoiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    gap: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  invoiceIconSlot: {
    width: 26,
    alignItems: 'center',
    flexShrink: 0,
  },
  invoiceMeta: { flex: 1 },
  invoiceDate: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    marginTop: 4,
  },
  invoiceStatus: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 11,
    letterSpacing: 0.44,
    textTransform: 'uppercase',
    flexShrink: 0,
  },
  invoiceAmount: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 16,
  },
  accordionToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 28,
    paddingVertical: 14,
    borderTopWidth: 1,
  },
  accordionTitle: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 16,
  },
  matrixPad: {
    paddingHorizontal: 20,
    paddingTop: 4,
  },
  matrixHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  matrixHeadSpacer: { flex: 1 },
  matrixHeadFree: {
    width: 64,
    textAlign: 'center',
    fontFamily: 'Rubik_500Medium',
    fontSize: 11,
    letterSpacing: 0.66,
    textTransform: 'uppercase',
  },
  matrixHeadPro: {
    width: 92,
    textAlign: 'center',
    fontFamily: 'Rubik_500Medium',
    fontSize: 11,
    letterSpacing: 0.66,
    textTransform: 'uppercase',
  },
  matrixCategoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 16,
    paddingBottom: 6,
  },
  matrixCategoryText: {
    fontFamily: 'Rubik_500Medium',
    fontSize: 11,
    letterSpacing: 0.66,
    textTransform: 'uppercase',
  },
  matrixRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderTopWidth: 1,
  },
  matrixLabel: {
    flex: 1,
    fontFamily: 'Rubik_400Regular',
    fontSize: 14,
    paddingRight: 10,
  },
  matrixCellFree: {
    width: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  matrixCellPro: {
    width: 92,
    alignItems: 'center',
    justifyContent: 'center',
  },
  matrixCellText: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 13,
    textAlign: 'center',
  },
  matrixYearlyCell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  footerBar: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    gap: 8,
    borderTopWidth: 1,
  },
  footerEcho: {
    fontFamily: 'Roboto_400Regular',
    fontSize: 12,
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
  },
  footerTerms: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 12,
    textAlign: 'center',
  },
  footerError: {
    fontFamily: 'Rubik_400Regular',
    fontSize: 12,
    textAlign: 'center',
  },
})
