/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Orbit.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const GetApiAccountabilityPairsResponse = zod.unknown()


export const PostApiAccountabilityPairsBody = zod.object({
  "buddyUserId": zod.uuid(),
  "cadence": zod.number(),
  "habitIds": zod.array(zod.uuid())
})

export const PostApiAccountabilityPairsResponse = zod.unknown()


export const PostApiAccountabilityPairsPairIdAcceptParams = zod.object({
  "pairId": zod.uuid()
})

export const PostApiAccountabilityPairsPairIdAcceptBody = zod.object({
  "habitIds": zod.array(zod.uuid())
})

export const PostApiAccountabilityPairsPairIdAcceptResponse = zod.void()


export const DeleteApiAccountabilityPairsPairIdParams = zod.object({
  "pairId": zod.uuid()
})

export const DeleteApiAccountabilityPairsPairIdResponse = zod.void()


export const PutApiAccountabilityPairsPairIdHabitsParams = zod.object({
  "pairId": zod.uuid()
})

export const PutApiAccountabilityPairsPairIdHabitsBody = zod.object({
  "habitIds": zod.array(zod.uuid())
})

export const PutApiAccountabilityPairsPairIdHabitsResponse = zod.void()


export const GetApiAccountabilityPairsPairIdCheckInsParams = zod.object({
  "pairId": zod.uuid()
})

export const GetApiAccountabilityPairsPairIdCheckInsResponse = zod.unknown()


export const PostApiAccountabilityPairsPairIdCheckInsParams = zod.object({
  "pairId": zod.uuid()
})

export const PostApiAccountabilityPairsPairIdCheckInsBody = zod.object({
  "note": zod.string().nullable()
})

export const PostApiAccountabilityPairsPairIdCheckInsResponse = zod.unknown()


export const PostApiAchievementsReportEventBody = zod.object({
  "eventKey": zod.string()
})

export const PostApiAchievementsReportEventResponse = zod.unknown()


export const PostApiAdminMarketingBroadcastBody = zod.object({
  "subjectEn": zod.string(),
  "subjectPt": zod.string(),
  "bodyHtmlEn": zod.string(),
  "bodyHtmlPt": zod.string(),
  "testEmail": zod.string().nullable()
})

export const PostApiAdminMarketingBroadcastResponse = zod.void()


export const GetApiAiCapabilitiesResponse = zod.unknown()


export const GetApiAiOperationsResponse = zod.unknown()


export const GetApiAiDataCatalogResponse = zod.unknown()


export const GetApiAiSurfacesResponse = zod.unknown()


export const PostApiAiPendingOperationsIdConfirmParams = zod.object({
  "id": zod.uuid()
})

export const PostApiAiPendingOperationsIdConfirmResponse = zod.unknown()


export const PostApiAiPendingOperationsIdStepUpParams = zod.object({
  "id": zod.uuid()
})

export const postApiAiPendingOperationsIdStepUpBodyTwoLanguageDefault = `en`;

export const PostApiAiPendingOperationsIdStepUpBody = zod.union([zod.null(),zod.object({
  "language": zod.string().default(postApiAiPendingOperationsIdStepUpBodyTwoLanguageDefault)
})])

export const PostApiAiPendingOperationsIdStepUpResponse = zod.unknown()


export const PostApiAiPendingOperationsIdStepUpVerifyParams = zod.object({
  "id": zod.uuid()
})

export const PostApiAiPendingOperationsIdStepUpVerifyBody = zod.object({
  "challengeId": zod.uuid(),
  "code": zod.string()
})

export const PostApiAiPendingOperationsIdStepUpVerifyResponse = zod.unknown()


export const PostApiAiPendingOperationsIdExecuteParams = zod.object({
  "id": zod.uuid()
})

export const PostApiAiPendingOperationsIdExecuteBody = zod.object({
  "confirmationToken": zod.string()
})

export const PostApiAiPendingOperationsIdExecuteResponse = zod.unknown()


export const PostApiAiClarificationsOperationIdResolveParams = zod.object({
  "operationId": zod.uuid()
})

export const PostApiAiClarificationsOperationIdResolveBody = zod.object({
  "value": zod.string()
})

export const PostApiAiClarificationsOperationIdResolveResponse = zod.unknown()


export const postApiApiKeysBodyIsReadOnlyDefault = false;

export const PostApiApiKeysBody = zod.object({
  "name": zod.string(),
  "scopes": zod.array(zod.string()).nullish(),
  "isReadOnly": zod.boolean().default(postApiApiKeysBodyIsReadOnlyDefault),
  "expiresAtUtc": zod.iso.datetime({"offset":true}).nullish()
})

export const PostApiApiKeysResponse = zod.void()


export const GetApiApiKeysResponse = zod.unknown()


export const DeleteApiApiKeysIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiApiKeysIdResponse = zod.void()


export const postApiAuthSendCodeBodyLanguageDefault = `en`;

export const PostApiAuthSendCodeBody = zod.object({
  "email": zod.string(),
  "language": zod.string().default(postApiAuthSendCodeBodyLanguageDefault)
})

export const PostApiAuthSendCodeResponse = zod.unknown()


export const postApiAuthOperationsSendCodeBodyLanguageDefault = `en`;

export const PostApiAuthOperationsSendCodeBody = zod.object({
  "email": zod.string(),
  "language": zod.string().default(postApiAuthOperationsSendCodeBodyLanguageDefault)
})

export const PostApiAuthOperationsSendCodeResponse = zod.unknown()


export const postApiAuthVerifyCodeBodyLanguageDefault = `en`;

export const PostApiAuthVerifyCodeBody = zod.object({
  "email": zod.string(),
  "code": zod.string(),
  "language": zod.string().default(postApiAuthVerifyCodeBodyLanguageDefault),
  "referralCode": zod.string().nullish()
})

export const PostApiAuthVerifyCodeResponse = zod.unknown()


export const postApiAuthOperationsVerifyCodeBodyLanguageDefault = `en`;

export const PostApiAuthOperationsVerifyCodeBody = zod.object({
  "email": zod.string(),
  "code": zod.string(),
  "language": zod.string().default(postApiAuthOperationsVerifyCodeBodyLanguageDefault),
  "referralCode": zod.string().nullish()
})

export const PostApiAuthOperationsVerifyCodeResponse = zod.unknown()


export const postApiAuthGoogleBodyLanguageDefault = `en`;

export const PostApiAuthGoogleBody = zod.object({
  "accessToken": zod.string(),
  "language": zod.string().default(postApiAuthGoogleBodyLanguageDefault),
  "googleAccessToken": zod.string().nullish(),
  "googleRefreshToken": zod.string().nullish(),
  "referralCode": zod.string().nullish()
})

export const PostApiAuthGoogleResponse = zod.unknown()


export const postApiAuthOperationsGoogleBodyLanguageDefault = `en`;

export const PostApiAuthOperationsGoogleBody = zod.object({
  "accessToken": zod.string(),
  "language": zod.string().default(postApiAuthOperationsGoogleBodyLanguageDefault),
  "googleAccessToken": zod.string().nullish(),
  "googleRefreshToken": zod.string().nullish(),
  "referralCode": zod.string().nullish()
})

export const PostApiAuthOperationsGoogleResponse = zod.unknown()


export const PostApiAuthRefreshBody = zod.object({
  "refreshToken": zod.string()
})

export const PostApiAuthRefreshResponse = zod.unknown()


export const PostApiAuthOperationsRefreshBody = zod.object({
  "refreshToken": zod.string()
})

export const PostApiAuthOperationsRefreshResponse = zod.unknown()


export const PostApiAuthLogoutBody = zod.object({
  "refreshToken": zod.string()
})

export const PostApiAuthLogoutResponse = zod.unknown()


export const PostApiAuthOperationsLogoutBody = zod.object({
  "refreshToken": zod.string()
})

export const PostApiAuthOperationsLogoutResponse = zod.unknown()


export const PostApiAuthRequestDeletionResponse = zod.unknown()


export const PostApiAuthConfirmDeletionBody = zod.object({
  "code": zod.string()
})

export const PostApiAuthConfirmDeletionResponse = zod.unknown()


export const GetApiCalendarEventsResponse = zod.unknown()


export const GetApiCalendarCalendarsResponse = zod.unknown()


export const PutApiCalendarSelectedCalendarsBody = zod.object({
  "calendarIds": zod.array(zod.string()).nullable()
})

export const PutApiCalendarSelectedCalendarsResponse = zod.void()


export const PutApiCalendarDismissResponse = zod.void()


export const GetApiCalendarAutoSyncStateResponse = zod.unknown()


export const PutApiCalendarAutoSyncBody = zod.object({
  "enabled": zod.boolean().nullable()
})

export const PutApiCalendarAutoSyncResponse = zod.unknown()


export const GetApiCalendarAutoSyncSuggestionsResponse = zod.unknown()


export const PutApiCalendarAutoSyncSuggestionsIdDismissParams = zod.object({
  "id": zod.uuid()
})

export const PutApiCalendarAutoSyncSuggestionsIdDismissResponse = zod.void()


export const PostApiCalendarAutoSyncRunResponse = zod.unknown()


export const postApiChallengesBodyTargetCountRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const PostApiChallengesBody = zod.object({
  "type": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "targetCount": zod.union([zod.number(),zod.stringFormat('int32', postApiChallengesBodyTargetCountRegExpTwo)]).nullable(),
  "periodStartUtc": zod.iso.date(),
  "periodEndUtc": zod.iso.date().nullable(),
  "linkedHabitIds": zod.array(zod.uuid()).nullable(),
  "invitedFriendUserIds": zod.array(zod.uuid()).nullable()
})

export const PostApiChallengesResponse = zod.unknown()


export const GetApiChallengesResponse = zod.unknown()


export const PostApiChallengesJoinBody = zod.object({
  "code": zod.string(),
  "linkedHabitIds": zod.array(zod.uuid()).nullable()
})

export const PostApiChallengesJoinResponse = zod.void()


export const DeleteApiChallengesChallengeIdLeaveParams = zod.object({
  "challengeId": zod.uuid()
})

export const DeleteApiChallengesChallengeIdLeaveResponse = zod.void()


export const PutApiChallengesChallengeIdHabitsParams = zod.object({
  "challengeId": zod.uuid()
})

export const PutApiChallengesChallengeIdHabitsBody = zod.object({
  "habitIds": zod.array(zod.uuid()).nullable()
})

export const PutApiChallengesChallengeIdHabitsResponse = zod.void()


export const GetApiChallengesChallengeIdParams = zod.object({
  "challengeId": zod.uuid()
})

export const GetApiChallengesChallengeIdResponse = zod.unknown()


export const PostApiChatBody = zod.object({
  "message": zod.string().optional()
}).and(zod.object({
  "history": zod.string().optional()
})).and(zod.object({
  "image": zod.instanceof(File).optional()
})).and(zod.object({
  "clientContext": zod.string().optional()
})).and(zod.object({
  "confirmationToken": zod.string().optional()
}))

export const PostApiChatResponse = zod.unknown()


export const PostApiChatStreamBody = zod.object({
  "message": zod.string().optional()
}).and(zod.object({
  "history": zod.string().optional()
})).and(zod.object({
  "image": zod.instanceof(File).optional()
})).and(zod.object({
  "clientContext": zod.string().optional()
})).and(zod.object({
  "confirmationToken": zod.string().optional()
}))

export const PostApiChatStreamResponse = zod.unknown()


export const PostApiChatTranscribeBody = zod.object({
  "audio": zod.instanceof(File).optional()
})

export const PostApiChatTranscribeResponse = zod.unknown()


export const GetApiChecklistTemplatesResponse = zod.unknown()


export const PostApiChecklistTemplatesBody = zod.object({
  "name": zod.string(),
  "items": zod.array(zod.string())
})

export const PostApiChecklistTemplatesResponse = zod.void()


export const DeleteApiChecklistTemplatesIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiChecklistTemplatesIdResponse = zod.void()


export const GetApiConfigResponse = zod.unknown()


export const GetApiFriendsResponse = zod.unknown()


export const GetApiFriendsUserIdProfileParams = zod.object({
  "userId": zod.uuid()
})

export const GetApiFriendsUserIdProfileResponse = zod.unknown()


export const GetApiFriendsInvitePreviewQueryParams = zod.object({
  "code": zod.string().optional()
})

export const GetApiFriendsInvitePreviewResponse = zod.unknown()


export const getApiFriendsFeedQueryPageSizeRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetApiFriendsFeedQueryParams = zod.object({
  "cursor": zod.string().optional(),
  "pageSize": zod.union([zod.number(),zod.stringFormat('int32', getApiFriendsFeedQueryPageSizeRegExpTwo)]).optional()
})

export const GetApiFriendsFeedResponse = zod.unknown()


export const getApiFriendsCheersQueryDirectionDefault = `received`;

export const GetApiFriendsCheersQueryParams = zod.object({
  "direction": zod.string().default(getApiFriendsCheersQueryDirectionDefault)
})

export const GetApiFriendsCheersResponse = zod.unknown()


export const PostApiFriendsCheersBody = zod.object({
  "recipientId": zod.uuid(),
  "habitId": zod.uuid().nullable(),
  "note": zod.string().nullable()
})

export const PostApiFriendsCheersResponse = zod.unknown()


export const PostApiFriendsRequestsBody = zod.object({
  "handle": zod.string().nullable(),
  "referralCode": zod.string().nullable()
})

export const PostApiFriendsRequestsResponse = zod.unknown()


export const PostApiFriendsRequestsFriendshipIdAcceptParams = zod.object({
  "friendshipId": zod.uuid()
})

export const PostApiFriendsRequestsFriendshipIdAcceptResponse = zod.void()


export const DeleteApiFriendsFriendUserIdParams = zod.object({
  "friendUserId": zod.uuid()
})

export const DeleteApiFriendsFriendUserIdResponse = zod.void()


export const PostApiFriendsBlockBody = zod.object({
  "blockedUserId": zod.uuid()
})

export const PostApiFriendsBlockResponse = zod.void()


export const DeleteApiFriendsBlockBlockedUserIdParams = zod.object({
  "blockedUserId": zod.uuid()
})

export const DeleteApiFriendsBlockBlockedUserIdResponse = zod.void()


export const PostApiFriendsReportBody = zod.object({
  "reportedUserId": zod.uuid(),
  "reason": zod.number(),
  "details": zod.string().nullable(),
  "cheerId": zod.uuid().nullable()
})

export const PostApiFriendsReportResponse = zod.unknown()


export const GetApiGamificationProfileResponse = zod.unknown()


export const GetApiGamificationAchievementsResponse = zod.unknown()


export const GetApiGamificationStreakResponse = zod.unknown()


export const GetApiGamificationRecapQueryParams = zod.object({
  "period": zod.string().optional()
})

export const GetApiGamificationRecapResponse = zod.unknown()


export const GetApiGamificationStreakHistoryQueryParams = zod.object({
  "dateFrom": zod.iso.date().optional(),
  "dateTo": zod.iso.date().optional()
})

export const GetApiGamificationStreakHistoryResponse = zod.unknown()


export const GetApiGamificationXpHistoryQueryParams = zod.object({
  "dateFrom": zod.iso.date().optional(),
  "dateTo": zod.iso.date().optional()
})

export const GetApiGamificationXpHistoryResponse = zod.unknown()


export const getApiGoalsQueryPageDefaultOne = 1;
export const getApiGoalsQueryPageDefaultTwo = 1;
export const getApiGoalsQueryPageRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getApiGoalsQueryPageDefault = 1;
export const getApiGoalsQueryPageSizeDefaultOne = 50;
export const getApiGoalsQueryPageSizeDefaultTwo = 50;
export const getApiGoalsQueryPageSizeRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getApiGoalsQueryPageSizeDefault = 50;

export const GetApiGoalsQueryParams = zod.object({
  "status": zod.number().optional(),
  "page": zod.union([zod.number().default(getApiGoalsQueryPageDefaultOne),zod.stringFormat('int32', getApiGoalsQueryPageRegExpTwo).default(getApiGoalsQueryPageDefaultTwo)]).optional(),
  "pageSize": zod.union([zod.number().default(getApiGoalsQueryPageSizeDefaultOne),zod.stringFormat('int32', getApiGoalsQueryPageSizeRegExpTwo).default(getApiGoalsQueryPageSizeDefaultTwo)]).optional()
})

export const GetApiGoalsResponse = zod.unknown()


export const postApiGoalsBodyTargetValueRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const postApiGoalsBodyTypeDefault = 0;

export const PostApiGoalsBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "targetValue": zod.union([zod.number(),zod.stringFormat('double', postApiGoalsBodyTargetValueRegExpTwo)]),
  "unit": zod.string(),
  "deadline": zod.iso.date().nullish(),
  "type": zod.number().default(postApiGoalsBodyTypeDefault)
})

export const PostApiGoalsResponse = zod.void()


export const GetApiGoalsIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiGoalsIdResponse = zod.unknown()


export const PutApiGoalsIdParams = zod.object({
  "id": zod.uuid()
})

export const putApiGoalsIdBodyTargetValueRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const PutApiGoalsIdBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "targetValue": zod.union([zod.number(),zod.stringFormat('double', putApiGoalsIdBodyTargetValueRegExpTwo)]),
  "unit": zod.string(),
  "deadline": zod.iso.date().nullish()
})

export const PutApiGoalsIdResponse = zod.void()


export const DeleteApiGoalsIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiGoalsIdResponse = zod.void()


export const PutApiGoalsIdProgressParams = zod.object({
  "id": zod.uuid()
})

export const putApiGoalsIdProgressBodyCurrentValueRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');


export const PutApiGoalsIdProgressBody = zod.object({
  "currentValue": zod.union([zod.number(),zod.stringFormat('double', putApiGoalsIdProgressBodyCurrentValueRegExpTwo)]),
  "note": zod.string().nullish()
})

export const PutApiGoalsIdProgressResponse = zod.void()


export const PutApiGoalsIdStatusParams = zod.object({
  "id": zod.uuid()
})

export const PutApiGoalsIdStatusBody = zod.object({
  "status": zod.number()
})

export const PutApiGoalsIdStatusResponse = zod.void()


export const putApiGoalsReorderBodyPositionsItemPositionRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const PutApiGoalsReorderBody = zod.object({
  "positions": zod.array(zod.object({
  "id": zod.uuid(),
  "position": zod.union([zod.number(),zod.stringFormat('int32', putApiGoalsReorderBodyPositionsItemPositionRegExpTwo)])
}))
})

export const PutApiGoalsReorderResponse = zod.void()


export const PutApiGoalsGoalIdHabitsParams = zod.object({
  "goalId": zod.uuid()
})

export const PutApiGoalsGoalIdHabitsBody = zod.object({
  "habitIds": zod.array(zod.uuid())
})

export const PutApiGoalsGoalIdHabitsResponse = zod.void()


export const GetApiGoalsIdDetailParams = zod.object({
  "id": zod.uuid()
})

export const GetApiGoalsIdDetailResponse = zod.unknown()


export const GetApiGoalsIdMetricsParams = zod.object({
  "id": zod.uuid()
})

export const GetApiGoalsIdMetricsResponse = zod.unknown()


export const GetApiGoalsIdProgressHistoryParams = zod.object({
  "id": zod.uuid()
})

export const GetApiGoalsIdProgressHistoryQueryParams = zod.object({
  "dateFrom": zod.iso.date().optional(),
  "dateTo": zod.iso.date().optional()
})

export const GetApiGoalsIdProgressHistoryResponse = zod.unknown()


export const getApiGoalsReviewQueryLanguageDefault = `en`;

export const GetApiGoalsReviewQueryParams = zod.object({
  "language": zod.string().default(getApiGoalsReviewQueryLanguageDefault)
})

export const GetApiGoalsReviewResponse = zod.unknown()


export const PostApiGoalsIdRestoreParams = zod.object({
  "id": zod.uuid()
})

export const PostApiGoalsIdRestoreResponse = zod.void()


export const GetApiHabitsCountResponse = zod.unknown()


export const GetApiHabitsWidgetResponse = zod.unknown()


export const getApiHabitsQueryPageRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const getApiHabitsQueryPageSizeRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const GetApiHabitsQueryParams = zod.object({
  "DateFrom": zod.iso.date().optional(),
  "DateTo": zod.iso.date().optional(),
  "IncludeOverdue": zod.boolean().optional(),
  "Search": zod.string().optional(),
  "FrequencyUnit": zod.string().optional(),
  "IsCompleted": zod.boolean().optional(),
  "TagIds": zod.array(zod.uuid()).optional(),
  "IsGeneral": zod.boolean().optional(),
  "Page": zod.union([zod.number(),zod.stringFormat('int32', getApiHabitsQueryPageRegExpTwo)]).optional(),
  "PageSize": zod.union([zod.number(),zod.stringFormat('int32', getApiHabitsQueryPageSizeRegExpTwo)]).optional(),
  "IncludeGeneral": zod.boolean().optional()
})

export const GetApiHabitsResponse = zod.unknown()


export const postApiHabitsBodyFrequencyQuantityRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const postApiHabitsBodyIsBadHabitDefault = false;
export const postApiHabitsBodyReminderEnabledDefault = false;
export const postApiHabitsBodyReminderTimesItemRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const postApiHabitsBodySlipAlertEnabledDefault = false;
export const postApiHabitsBodyIsGeneralDefault = false;
export const postApiHabitsBodyIsFlexibleDefault = false;

export const PostApiHabitsBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "frequencyUnit": zod.union([zod.null(),zod.number()]),
  "frequencyQuantity": zod.union([zod.number(),zod.stringFormat('int32', postApiHabitsBodyFrequencyQuantityRegExpTwo)]).nullable(),
  "days": zod.array(zod.number()).nullish(),
  "isBadHabit": zod.boolean().default(postApiHabitsBodyIsBadHabitDefault),
  "subHabits": zod.array(zod.string()).nullish(),
  "dueDate": zod.iso.date().nullish(),
  "dueTime": zod.iso.time({}).nullish(),
  "dueEndTime": zod.iso.time({}).nullish(),
  "reminderEnabled": zod.boolean().default(postApiHabitsBodyReminderEnabledDefault),
  "reminderTimes": zod.array(zod.union([zod.number(),zod.stringFormat('int32', postApiHabitsBodyReminderTimesItemRegExpTwo)])).nullish(),
  "scheduledReminders": zod.array(zod.object({
  "when": zod.enum(['same_day', 'day_before']),
  "time": zod.iso.time({})
})).nullish(),
  "slipAlertEnabled": zod.boolean().default(postApiHabitsBodySlipAlertEnabledDefault),
  "tagIds": zod.array(zod.uuid()).nullish(),
  "checklistItems": zod.array(zod.object({
  "text": zod.string(),
  "isChecked": zod.boolean()
})).nullish(),
  "isGeneral": zod.boolean().default(postApiHabitsBodyIsGeneralDefault),
  "endDate": zod.iso.date().nullish(),
  "isFlexible": zod.boolean().default(postApiHabitsBodyIsFlexibleDefault),
  "goalIds": zod.array(zod.uuid()).nullish(),
  "emoji": zod.string().nullish()
})

export const PostApiHabitsResponse = zod.void()


export const GetApiHabitsCalendarMonthQueryParams = zod.object({
  "dateFrom": zod.iso.date().optional(),
  "dateTo": zod.iso.date().optional()
})

export const GetApiHabitsCalendarMonthResponse = zod.unknown()


export const GetApiHabitsTrendsQueryParams = zod.object({
  "dateFrom": zod.iso.date().optional(),
  "dateTo": zod.iso.date().optional()
})

export const GetApiHabitsTrendsResponse = zod.unknown()


export const getApiHabitsSummaryQueryLanguageDefault = `en`;

export const GetApiHabitsSummaryQueryParams = zod.object({
  "dateFrom": zod.iso.date().optional(),
  "dateTo": zod.iso.date().optional(),
  "language": zod.string().default(getApiHabitsSummaryQueryLanguageDefault)
})

export const GetApiHabitsSummaryResponse = zod.unknown()


export const getApiHabitsRetrospectiveQueryLanguageDefault = `en`;

export const GetApiHabitsRetrospectiveQueryParams = zod.object({
  "period": zod.string().optional(),
  "language": zod.string().default(getApiHabitsRetrospectiveQueryLanguageDefault)
})

export const GetApiHabitsRetrospectiveResponse = zod.unknown()


export const GetApiHabitsIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiHabitsIdResponse = zod.unknown()


export const PutApiHabitsIdParams = zod.object({
  "id": zod.uuid()
})

export const putApiHabitsIdBodyFrequencyQuantityRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const putApiHabitsIdBodyIsBadHabitDefault = false;
export const putApiHabitsIdBodyReminderTimesItemRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const PutApiHabitsIdBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "frequencyUnit": zod.union([zod.null(),zod.number()]),
  "frequencyQuantity": zod.union([zod.number(),zod.stringFormat('int32', putApiHabitsIdBodyFrequencyQuantityRegExpTwo)]).nullable(),
  "days": zod.array(zod.number()).nullish(),
  "isBadHabit": zod.boolean().default(putApiHabitsIdBodyIsBadHabitDefault),
  "dueDate": zod.iso.date().nullish(),
  "dueTime": zod.iso.time({}).nullish(),
  "dueEndTime": zod.iso.time({}).nullish(),
  "reminderEnabled": zod.boolean().nullish(),
  "reminderTimes": zod.array(zod.union([zod.number(),zod.stringFormat('int32', putApiHabitsIdBodyReminderTimesItemRegExpTwo)])).nullish(),
  "scheduledReminders": zod.array(zod.object({
  "when": zod.enum(['same_day', 'day_before']),
  "time": zod.iso.time({})
})).nullish(),
  "slipAlertEnabled": zod.boolean().nullish(),
  "checklistItems": zod.array(zod.object({
  "text": zod.string(),
  "isChecked": zod.boolean()
})).nullish(),
  "isGeneral": zod.boolean().nullish(),
  "endDate": zod.iso.date().nullish(),
  "clearEndDate": zod.boolean().nullish(),
  "isFlexible": zod.boolean().nullish(),
  "goalIds": zod.array(zod.uuid()).nullish(),
  "emoji": zod.string().nullish()
})

export const PutApiHabitsIdResponse = zod.void()


export const DeleteApiHabitsIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiHabitsIdResponse = zod.void()


export const GetApiHabitsIdDetailParams = zod.object({
  "id": zod.uuid()
})

export const GetApiHabitsIdDetailResponse = zod.unknown()


export const GetApiHabitsIdRescheduleSuggestionParams = zod.object({
  "id": zod.uuid()
})

export const getApiHabitsIdRescheduleSuggestionQueryLanguageDefault = `en`;

export const GetApiHabitsIdRescheduleSuggestionQueryParams = zod.object({
  "language": zod.string().default(getApiHabitsIdRescheduleSuggestionQueryLanguageDefault)
})

export const GetApiHabitsIdRescheduleSuggestionResponse = zod.unknown()


export const postApiHabitsSuggestSetupBodyLanguageDefault = `en`;

export const PostApiHabitsSuggestSetupBody = zod.object({
  "title": zod.string(),
  "language": zod.string().default(postApiHabitsSuggestSetupBodyLanguageDefault)
})

export const PostApiHabitsSuggestSetupResponse = zod.unknown()


export const PostApiHabitsIdLogParams = zod.object({
  "id": zod.uuid()
})

export const PostApiHabitsIdLogBody = zod.union([zod.null(),zod.object({
  "date": zod.iso.date().nullish()
})])

export const PostApiHabitsIdLogResponse = zod.unknown()


export const PostApiHabitsIdSkipParams = zod.object({
  "id": zod.uuid()
})

export const PostApiHabitsIdSkipBody = zod.union([zod.null(),zod.object({
  "date": zod.iso.date().nullish()
})])

export const PostApiHabitsIdSkipResponse = zod.void()


export const PutApiHabitsIdChecklistParams = zod.object({
  "id": zod.uuid()
})

export const PutApiHabitsIdChecklistBody = zod.object({
  "checklistItems": zod.array(zod.object({
  "text": zod.string(),
  "isChecked": zod.boolean()
}))
})

export const PutApiHabitsIdChecklistResponse = zod.void()


export const PostApiHabitsIdRestoreParams = zod.object({
  "id": zod.uuid()
})

export const PostApiHabitsIdRestoreResponse = zod.void()


export const GetApiHabitsIdLogsParams = zod.object({
  "id": zod.uuid()
})

export const GetApiHabitsIdLogsResponse = zod.unknown()


export const GetApiHabitsIdMetricsParams = zod.object({
  "id": zod.uuid()
})

export const GetApiHabitsIdMetricsResponse = zod.unknown()


export const postApiHabitsBulkBodyHabitsItemFrequencyQuantityRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const postApiHabitsBulkBodyHabitsItemIsBadHabitDefault = false;
export const postApiHabitsBulkBodyHabitsItemReminderEnabledDefault = false;
export const postApiHabitsBulkBodyHabitsItemReminderTimesItemRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const postApiHabitsBulkBodyHabitsItemIsGeneralDefault = false;
export const postApiHabitsBulkBodyHabitsItemIsFlexibleDefault = false;
export const postApiHabitsBulkBodyFromSyncReviewDefault = false;

export const PostApiHabitsBulkBody = zod.object({
  "habits": zod.array(zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "frequencyUnit": zod.union([zod.null(),zod.number()]),
  "frequencyQuantity": zod.union([zod.number(),zod.stringFormat('int32', postApiHabitsBulkBodyHabitsItemFrequencyQuantityRegExpTwo)]).nullable(),
  "days": zod.array(zod.number()).nullish(),
  "isBadHabit": zod.boolean().default(postApiHabitsBulkBodyHabitsItemIsBadHabitDefault),
  "dueDate": zod.iso.date().nullish(),
  "dueTime": zod.iso.time({}).nullish(),
  "dueEndTime": zod.iso.time({}).nullish(),
  "reminderEnabled": zod.boolean().default(postApiHabitsBulkBodyHabitsItemReminderEnabledDefault),
  "reminderTimes": zod.array(zod.union([zod.number(),zod.stringFormat('int32', postApiHabitsBulkBodyHabitsItemReminderTimesItemRegExpTwo)])).nullish(),
  "scheduledReminders": zod.array(zod.object({
  "when": zod.enum(['same_day', 'day_before']),
  "time": zod.iso.time({})
})).nullish(),
  "subHabits": zod.array(zod.unknown()).nullish(),
  "isGeneral": zod.boolean().default(postApiHabitsBulkBodyHabitsItemIsGeneralDefault),
  "endDate": zod.iso.date().nullish(),
  "isFlexible": zod.boolean().default(postApiHabitsBulkBodyHabitsItemIsFlexibleDefault),
  "checklistItems": zod.array(zod.object({
  "text": zod.string(),
  "isChecked": zod.boolean()
})).nullish(),
  "googleEventId": zod.string().nullish(),
  "emoji": zod.string().nullish(),
  "tags": zod.array(zod.string()).nullish()
})),
  "fromSyncReview": zod.boolean().default(postApiHabitsBulkBodyFromSyncReviewDefault)
})

export const PostApiHabitsBulkResponse = zod.void()


export const DeleteApiHabitsBulkBody = zod.object({
  "habitIds": zod.array(zod.uuid())
})

export const DeleteApiHabitsBulkResponse = zod.unknown()


export const PostApiHabitsBulkLogBody = zod.object({
  "items": zod.array(zod.object({
  "habitId": zod.uuid(),
  "date": zod.iso.date().nullish()
}))
})

export const PostApiHabitsBulkLogResponse = zod.unknown()


export const PostApiHabitsBulkSkipBody = zod.object({
  "items": zod.array(zod.object({
  "habitId": zod.uuid(),
  "date": zod.iso.date().nullish()
}))
})

export const PostApiHabitsBulkSkipResponse = zod.unknown()


export const putApiHabitsReorderBodyPositionsItemPositionRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const PutApiHabitsReorderBody = zod.object({
  "positions": zod.array(zod.object({
  "habitId": zod.uuid(),
  "position": zod.union([zod.number(),zod.stringFormat('int32', putApiHabitsReorderBodyPositionsItemPositionRegExpTwo)])
}))
})

export const PutApiHabitsReorderResponse = zod.void()


export const PutApiHabitsIdParentParams = zod.object({
  "id": zod.uuid()
})

export const PutApiHabitsIdParentBody = zod.object({
  "parentId": zod.uuid().nullable()
})

export const PutApiHabitsIdParentResponse = zod.void()


export const PostApiHabitsIdDuplicateParams = zod.object({
  "id": zod.uuid()
})

export const PostApiHabitsIdDuplicateResponse = zod.void()


export const PostApiHabitsParentIdSubHabitsParams = zod.object({
  "parentId": zod.uuid()
})

export const postApiHabitsParentIdSubHabitsBodyFrequencyQuantityRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const postApiHabitsParentIdSubHabitsBodyIsBadHabitDefault = false;
export const postApiHabitsParentIdSubHabitsBodyReminderEnabledDefault = false;
export const postApiHabitsParentIdSubHabitsBodyReminderTimesItemRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const postApiHabitsParentIdSubHabitsBodySlipAlertEnabledDefault = false;
export const postApiHabitsParentIdSubHabitsBodyIsFlexibleDefault = false;

export const PostApiHabitsParentIdSubHabitsBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullish(),
  "frequencyUnit": zod.union([zod.null(),zod.number()]).optional(),
  "frequencyQuantity": zod.union([zod.number(),zod.stringFormat('int32', postApiHabitsParentIdSubHabitsBodyFrequencyQuantityRegExpTwo)]).nullish(),
  "days": zod.array(zod.number()).nullish(),
  "isBadHabit": zod.boolean().default(postApiHabitsParentIdSubHabitsBodyIsBadHabitDefault),
  "dueDate": zod.iso.date().nullish(),
  "dueTime": zod.iso.time({}).nullish(),
  "dueEndTime": zod.iso.time({}).nullish(),
  "reminderEnabled": zod.boolean().default(postApiHabitsParentIdSubHabitsBodyReminderEnabledDefault),
  "reminderTimes": zod.array(zod.union([zod.number(),zod.stringFormat('int32', postApiHabitsParentIdSubHabitsBodyReminderTimesItemRegExpTwo)])).nullish(),
  "scheduledReminders": zod.array(zod.object({
  "when": zod.enum(['same_day', 'day_before']),
  "time": zod.iso.time({})
})).nullish(),
  "slipAlertEnabled": zod.boolean().default(postApiHabitsParentIdSubHabitsBodySlipAlertEnabledDefault),
  "checklistItems": zod.array(zod.object({
  "text": zod.string(),
  "isChecked": zod.boolean()
})).nullish(),
  "tagIds": zod.array(zod.uuid()).nullish(),
  "endDate": zod.iso.date().nullish(),
  "isFlexible": zod.boolean().default(postApiHabitsParentIdSubHabitsBodyIsFlexibleDefault),
  "emoji": zod.string().nullish()
})

export const PostApiHabitsParentIdSubHabitsResponse = zod.void()


export const PutApiHabitsHabitIdGoalsParams = zod.object({
  "habitId": zod.uuid()
})

export const PutApiHabitsHabitIdGoalsBody = zod.object({
  "goalIds": zod.array(zod.uuid())
})

export const PutApiHabitsHabitIdGoalsResponse = zod.void()


export const PostApiMarketingUnsubscribeQueryParams = zod.object({
  "token": zod.string().optional()
})

export const PostApiMarketingUnsubscribeResponse = zod.unknown()


export const GetApiNotificationsResponse = zod.unknown()


export const PutApiNotificationsIdReadParams = zod.object({
  "id": zod.uuid()
})

export const PutApiNotificationsIdReadResponse = zod.void()


export const PutApiNotificationsReadAllResponse = zod.void()


export const DeleteApiNotificationsIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiNotificationsIdResponse = zod.void()


export const DeleteApiNotificationsAllResponse = zod.void()


export const PostApiNotificationsSubscribeBody = zod.object({
  "endpoint": zod.string(),
  "p256dh": zod.string(),
  "auth": zod.string()
})

export const PostApiNotificationsSubscribeResponse = zod.unknown()


export const PostApiNotificationsUnsubscribeBody = zod.object({
  "endpoint": zod.string(),
  "p256dh": zod.string(),
  "auth": zod.string()
})

export const PostApiNotificationsUnsubscribeResponse = zod.unknown()


export const PostApiNotificationsTestPushResponse = zod.unknown()


export const GetWellKnownOauthAuthorizationServerResponse = zod.unknown()


export const PostOauthRegisterBody = zod.unknown()

export const PostOauthRegisterResponse = zod.unknown()


export const GetWellKnownOauthProtectedResourceResponse = zod.unknown()


export const GetOauthAuthorizeQueryParams = zod.object({
  "client_id": zod.string().optional(),
  "redirect_uri": zod.string().optional(),
  "response_type": zod.string().optional(),
  "state": zod.string().optional(),
  "code_challenge": zod.string().optional(),
  "code_challenge_method": zod.string().optional()
})

export const GetOauthAuthorizeResponse = zod.unknown()


export const postOauthSendCodeBodyLanguageDefault = `en`;

export const PostOauthSendCodeBody = zod.object({
  "email": zod.string(),
  "language": zod.string().default(postOauthSendCodeBodyLanguageDefault)
})

export const PostOauthSendCodeResponse = zod.unknown()


export const postOauthVerifyCodeBodyLanguageDefault = `en`;

export const PostOauthVerifyCodeBody = zod.object({
  "email": zod.string(),
  "code": zod.string(),
  "language": zod.string().default(postOauthVerifyCodeBodyLanguageDefault),
  "referralCode": zod.string().nullish()
})

export const PostOauthVerifyCodeResponse = zod.unknown()


export const postOauthGoogleBodyLanguageDefault = `en`;

export const PostOauthGoogleBody = zod.object({
  "accessToken": zod.string(),
  "language": zod.string().default(postOauthGoogleBodyLanguageDefault),
  "googleAccessToken": zod.string().nullish(),
  "googleRefreshToken": zod.string().nullish(),
  "referralCode": zod.string().nullish()
})

export const PostOauthGoogleResponse = zod.unknown()


export const PostOauthTokenBody = zod.object({
  "grant_type": zod.string().optional()
}).and(zod.object({
  "code": zod.string().optional()
})).and(zod.object({
  "code_verifier": zod.string().optional()
})).and(zod.object({
  "client_id": zod.string().optional()
})).and(zod.object({
  "redirect_uri": zod.string().optional()
}))

export const PostOauthTokenResponse = zod.unknown()


export const GetApiProfileResponse = zod.unknown()


export const PutApiProfileTimezoneBody = zod.object({
  "timeZone": zod.string()
})

export const PutApiProfileTimezoneResponse = zod.void()


export const PutApiProfileNameBody = zod.object({
  "name": zod.string()
})

export const PutApiProfileNameResponse = zod.void()


export const PutApiProfileAiMemoryBody = zod.object({
  "enabled": zod.boolean()
})

export const PutApiProfileAiMemoryResponse = zod.void()


export const PutApiProfileAiSummaryBody = zod.object({
  "enabled": zod.boolean()
})

export const PutApiProfileAiSummaryResponse = zod.void()


export const PutApiProfileProactiveAstraBody = zod.object({
  "enabled": zod.boolean()
})

export const PutApiProfileProactiveAstraResponse = zod.void()


export const PutApiProfileLanguageBody = zod.object({
  "language": zod.string()
})

export const PutApiProfileLanguageResponse = zod.void()


export const putApiProfileWeekStartDayBodyWeekStartDayRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const PutApiProfileWeekStartDayBody = zod.object({
  "weekStartDay": zod.union([zod.number(),zod.stringFormat('int32', putApiProfileWeekStartDayBodyWeekStartDayRegExpTwo)])
})

export const PutApiProfileWeekStartDayResponse = zod.void()


export const PutApiProfileThemePreferenceBody = zod.object({
  "themePreference": zod.string().nullable()
})

export const PutApiProfileThemePreferenceResponse = zod.void()


export const PutApiProfileColorSchemeBody = zod.object({
  "colorScheme": zod.string().nullable()
})

export const PutApiProfileColorSchemeResponse = zod.void()


export const PutApiProfileOnboardingResponse = zod.void()


export const postApiProfileOnboardingApplyBodyHabitsItemFrequencyQuantityRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const postApiProfileOnboardingApplyBodyHabitsItemIsBadHabitDefault = false;
export const postApiProfileOnboardingApplyBodyHabitsItemIsGeneralDefault = false;
export const postApiProfileOnboardingApplyBodyHabitsItemIsFlexibleDefault = false;
export const postApiProfileOnboardingApplyBodyHabitsItemReminderEnabledDefault = false;
export const postApiProfileOnboardingApplyBodyHabitsItemReminderTimesItemRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const postApiProfileOnboardingApplyBodyFirstLogTwoHabitIndexRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');
export const postApiProfileOnboardingApplyBodyGoalTwoTargetValueRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$');
export const postApiProfileOnboardingApplyBodyGoalTwoTypeDefault = 0;
export const postApiProfileOnboardingApplyBodyWeekStartDayRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const PostApiProfileOnboardingApplyBody = zod.object({
  "habits": zod.array(zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "emoji": zod.string().nullable(),
  "frequencyUnit": zod.union([zod.null(),zod.number()]),
  "frequencyQuantity": zod.union([zod.number(),zod.stringFormat('int32', postApiProfileOnboardingApplyBodyHabitsItemFrequencyQuantityRegExpTwo)]).nullable(),
  "days": zod.array(zod.number()).nullish(),
  "isBadHabit": zod.boolean().default(postApiProfileOnboardingApplyBodyHabitsItemIsBadHabitDefault),
  "isGeneral": zod.boolean().default(postApiProfileOnboardingApplyBodyHabitsItemIsGeneralDefault),
  "isFlexible": zod.boolean().default(postApiProfileOnboardingApplyBodyHabitsItemIsFlexibleDefault),
  "dueDate": zod.iso.date().nullish(),
  "dueTime": zod.iso.time({}).nullish(),
  "reminderEnabled": zod.boolean().default(postApiProfileOnboardingApplyBodyHabitsItemReminderEnabledDefault),
  "reminderTimes": zod.array(zod.union([zod.number(),zod.stringFormat('int32', postApiProfileOnboardingApplyBodyHabitsItemReminderTimesItemRegExpTwo)])).nullish(),
  "checklistItems": zod.array(zod.object({
  "text": zod.string(),
  "isChecked": zod.boolean()
})).nullish()
})).nullable(),
  "firstLog": zod.union([zod.null(),zod.object({
  "habitIndex": zod.union([zod.number(),zod.stringFormat('int32', postApiProfileOnboardingApplyBodyFirstLogTwoHabitIndexRegExpTwo)]),
  "date": zod.iso.date()
})]),
  "goal": zod.union([zod.null(),zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "targetValue": zod.union([zod.number(),zod.stringFormat('double', postApiProfileOnboardingApplyBodyGoalTwoTargetValueRegExpTwo)]),
  "unit": zod.string(),
  "deadline": zod.iso.date().nullish(),
  "type": zod.number().default(postApiProfileOnboardingApplyBodyGoalTwoTypeDefault)
})]),
  "weekStartDay": zod.union([zod.number(),zod.stringFormat('int32', postApiProfileOnboardingApplyBodyWeekStartDayRegExpTwo)]).nullable(),
  "colorScheme": zod.string().nullable()
})

export const PostApiProfileOnboardingApplyResponse = zod.unknown()


export const PutApiProfileImportPromptDismissResponse = zod.void()


export const PutApiProfileTourResponse = zod.void()


export const DeleteApiProfileTourResponse = zod.void()


export const PutApiProfileHandleBody = zod.object({
  "handle": zod.string()
})

export const PutApiProfileHandleResponse = zod.void()


export const PutApiProfileSocialOptInBody = zod.object({
  "enabled": zod.boolean()
})

export const PutApiProfileSocialOptInResponse = zod.void()


export const PutApiProfileMarketingConsentBody = zod.object({
  "enabled": zod.boolean()
})

export const PutApiProfileMarketingConsentResponse = zod.void()


export const PutApiProfilePublicBody = zod.object({
  "enabled": zod.boolean(),
  "showStreak": zod.boolean(),
  "showLevel": zod.boolean(),
  "showAchievements": zod.boolean(),
  "showTopHabits": zod.boolean(),
  "regenerate": zod.boolean()
})

export const PutApiProfilePublicResponse = zod.unknown()


export const PostApiProfileResetResponse = zod.unknown()


export const GetApiProfileExportResponse = zod.unknown()


export const GetApiUSlugParams = zod.object({
  "slug": zod.string()
})

export const GetApiUSlugResponse = zod.unknown()


export const PostApiReferralsCodeResponse = zod.unknown()


export const GetApiReferralsStatsResponse = zod.unknown()


export const GetApiReferralsDashboardResponse = zod.unknown()


export const PostApiSubscriptionsCheckoutBody = zod.object({
  "interval": zod.string()
})

export const PostApiSubscriptionsCheckoutResponse = zod.unknown()


export const PostApiSubscriptionsPortalResponse = zod.unknown()


export const GetApiSubscriptionsStatusResponse = zod.unknown()


export const GetApiSubscriptionsBillingResponse = zod.unknown()


export const GetApiSubscriptionsPlansResponse = zod.unknown()


export const PostApiSubscriptionsAdRewardResponse = zod.unknown()


export const PostApiSubscriptionsWebhookResponse = zod.unknown()


export const PostApiSubscriptionsPlayVerifyBody = zod.object({
  "productId": zod.string(),
  "purchaseToken": zod.string()
})

export const PostApiSubscriptionsPlayVerifyResponse = zod.unknown()


export const PostApiSubscriptionsPlayRtdnResponse = zod.unknown()


export const PostApiSupportBody = zod.object({
  "name": zod.string(),
  "email": zod.string(),
  "subject": zod.string(),
  "message": zod.string()
})

export const PostApiSupportResponse = zod.unknown()


export const GetApiSyncV2ChangesQueryParams = zod.object({
  "since": zod.iso.datetime({"offset":true}).optional()
})

export const GetApiSyncV2ChangesResponse = zod.unknown()


export const PostApiSyncBatchBody = zod.object({
  "mutations": zod.array(zod.object({
  "entity": zod.string(),
  "action": zod.string(),
  "id": zod.uuid().nullable(),
  "data": zod.looseObject({

}).nullable()
}))
})

export const PostApiSyncBatchResponse = zod.unknown()


export const GetApiTagsResponse = zod.unknown()


export const PostApiTagsBody = zod.object({
  "name": zod.string(),
  "color": zod.string()
})

export const PostApiTagsResponse = zod.void()


export const PutApiTagsIdParams = zod.object({
  "id": zod.uuid()
})

export const PutApiTagsIdBody = zod.object({
  "name": zod.string(),
  "color": zod.string()
})

export const PutApiTagsIdResponse = zod.void()


export const DeleteApiTagsIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiTagsIdResponse = zod.void()


export const PostApiTagsIdRestoreParams = zod.object({
  "id": zod.uuid()
})

export const PostApiTagsIdRestoreResponse = zod.void()


export const PutApiTagsHabitIdAssignParams = zod.object({
  "habitId": zod.uuid()
})

export const PutApiTagsHabitIdAssignBody = zod.object({
  "tagIds": zod.array(zod.uuid())
})

export const PutApiTagsHabitIdAssignResponse = zod.void()


export const PostApiTagsSuggestBody = zod.object({
  "title": zod.string(),
  "description": zod.string().nullable(),
  "language": zod.string().nullable()
})

export const PostApiTagsSuggestResponse = zod.unknown()


export const postApiUploadsSignBodySizeBytesRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d*)$');


export const PostApiUploadsSignBody = zod.object({
  "contentType": zod.string(),
  "sizeBytes": zod.union([zod.number(),zod.stringFormat('int64', postApiUploadsSignBodySizeBytesRegExpTwo)])
})

export const PostApiUploadsSignResponse = zod.unknown()


export const GetApiUserFactsResponse = zod.unknown()


export const DeleteApiUserFactsIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiUserFactsIdResponse = zod.void()


export const DeleteApiUserFactsBulkBody = zod.object({
  "factIds": zod.array(zod.uuid())
})

export const DeleteApiUserFactsBulkResponse = zod.unknown()


export const postApiWaitlistBodyLanguageDefault = `en`;

export const PostApiWaitlistBody = zod.object({
  "email": zod.string(),
  "language": zod.string().default(postApiWaitlistBodyLanguageDefault)
})

export const PostApiWaitlistResponse = zod.unknown()
